// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"shop-goframe-micro-service-refacotor/app/order/internal/dao/internal"
)

// orderOutboxMessageDao is the data access object for the table order_outbox_message.
// You can define custom methods on it to extend its functionality as needed.
type orderOutboxMessageDao struct {
	*internal.OrderOutboxMessageDao
}

var (
	// OrderOutboxMessage is a globally accessible object for table order_outbox_message operations.
	OrderOutboxMessage = orderOutboxMessageDao{internal.NewOrderOutboxMessageDao()}
)

// Add your custom methods and functionality below.
