// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// refundInfoDao is the DAO object for table refund_info.
type refundInfoDao struct {
	model *gdb.Model
}

// RefundInfo is a globally accessible object for table refund_info operations.
var RefundInfo = refundInfoDao{}

// GetModel 获取退款模型实例
func (dao *refundInfoDao) GetModel() *gdb.Model {
	if dao.model == nil {
		// 延迟初始化，避免在测试环境中直接连接数据库
		dao.model = g.DB().Model("refund_info")
	}
	return dao.model
}

// Add your custom methods and functionality below.
