// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: recommend_goods_info/v1/recommend_goods_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service-refacotor/app/goods/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendGoodsInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendGoodsInfoGetListReq) Reset() {
	*x = RecommendGoodsInfoGetListReq{}
	mi := &file_recommend_goods_info_v1_recommend_goods_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendGoodsInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendGoodsInfoGetListReq) ProtoMessage() {}

func (x *RecommendGoodsInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_goods_info_v1_recommend_goods_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendGoodsInfoGetListReq.ProtoReflect.Descriptor instead.
func (*RecommendGoodsInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_recommend_goods_info_v1_recommend_goods_info_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendGoodsInfoGetListReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecommendGoodsInfoGetListReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RecommendGoodsItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品字段
	Id               uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"商品字段"`
	Name             string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price            uint64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	PicUrl           string `protobuf:"bytes,4,opt,name=PicUrl,proto3" json:"PicUrl,omitempty" dc:"主图"` // 主图
	Images           string `protobuf:"bytes,5,opt,name=Images,proto3" json:"Images,omitempty"`
	Level1CategoryId uint32 `protobuf:"varint,6,opt,name=level1_category_id,json=level1CategoryId,proto3" json:"level1_category_id,omitempty"`
	Level2CategoryId uint32 `protobuf:"varint,7,opt,name=level2_category_id,json=level2CategoryId,proto3" json:"level2_category_id,omitempty"`
	Level3CategoryId uint32 `protobuf:"varint,8,opt,name=level3_category_id,json=level3CategoryId,proto3" json:"level3_category_id,omitempty"`
	Brand            string `protobuf:"bytes,9,opt,name=brand,proto3" json:"brand,omitempty"`
	Stock            uint32 `protobuf:"varint,10,opt,name=stock,proto3" json:"stock,omitempty"`
	Sale             uint32 `protobuf:"varint,11,opt,name=sale,proto3" json:"sale,omitempty"`
	Tags             string `protobuf:"bytes,12,opt,name=tags,proto3" json:"tags,omitempty"`
	DetailInfo       string `protobuf:"bytes,13,opt,name=detail_info,json=detailInfo,proto3" json:"detail_info,omitempty"`
	Sort             uint32 `protobuf:"varint,14,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecommendGoodsItem) Reset() {
	*x = RecommendGoodsItem{}
	mi := &file_recommend_goods_info_v1_recommend_goods_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendGoodsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendGoodsItem) ProtoMessage() {}

func (x *RecommendGoodsItem) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_goods_info_v1_recommend_goods_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendGoodsItem.ProtoReflect.Descriptor instead.
func (*RecommendGoodsItem) Descriptor() ([]byte, []int) {
	return file_recommend_goods_info_v1_recommend_goods_info_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendGoodsItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecommendGoodsItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecommendGoodsItem) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RecommendGoodsItem) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *RecommendGoodsItem) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *RecommendGoodsItem) GetLevel1CategoryId() uint32 {
	if x != nil {
		return x.Level1CategoryId
	}
	return 0
}

func (x *RecommendGoodsItem) GetLevel2CategoryId() uint32 {
	if x != nil {
		return x.Level2CategoryId
	}
	return 0
}

func (x *RecommendGoodsItem) GetLevel3CategoryId() uint32 {
	if x != nil {
		return x.Level3CategoryId
	}
	return 0
}

func (x *RecommendGoodsItem) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *RecommendGoodsItem) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *RecommendGoodsItem) GetSale() uint32 {
	if x != nil {
		return x.Sale
	}
	return 0
}

func (x *RecommendGoodsItem) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *RecommendGoodsItem) GetDetailInfo() string {
	if x != nil {
		return x.DetailInfo
	}
	return ""
}

func (x *RecommendGoodsItem) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type RecommendGoodsInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*pbentity.GoodsInfo  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendGoodsInfoListResponse) Reset() {
	*x = RecommendGoodsInfoListResponse{}
	mi := &file_recommend_goods_info_v1_recommend_goods_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendGoodsInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendGoodsInfoListResponse) ProtoMessage() {}

func (x *RecommendGoodsInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_goods_info_v1_recommend_goods_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendGoodsInfoListResponse.ProtoReflect.Descriptor instead.
func (*RecommendGoodsInfoListResponse) Descriptor() ([]byte, []int) {
	return file_recommend_goods_info_v1_recommend_goods_info_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendGoodsInfoListResponse) GetList() []*pbentity.GoodsInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RecommendGoodsInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RecommendGoodsInfoGetListRes struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Data          *RecommendGoodsInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendGoodsInfoGetListRes) Reset() {
	*x = RecommendGoodsInfoGetListRes{}
	mi := &file_recommend_goods_info_v1_recommend_goods_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendGoodsInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendGoodsInfoGetListRes) ProtoMessage() {}

func (x *RecommendGoodsInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_goods_info_v1_recommend_goods_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendGoodsInfoGetListRes.ProtoReflect.Descriptor instead.
func (*RecommendGoodsInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_recommend_goods_info_v1_recommend_goods_info_proto_rawDescGZIP(), []int{3}
}

func (x *RecommendGoodsInfoGetListRes) GetData() *RecommendGoodsInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_recommend_goods_info_v1_recommend_goods_info_proto protoreflect.FileDescriptor

const file_recommend_goods_info_v1_recommend_goods_info_proto_rawDesc = "" +
	"\n" +
	"2recommend_goods_info/v1/recommend_goods_info.proto\x12\x11add_goods_info.v1\x1a\x19pbentity/goods_info.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\x1cRecommendGoodsInfoGetListReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\x91\x03\n" +
	"\x12RecommendGoodsItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x04R\x05price\x12\x16\n" +
	"\x06PicUrl\x18\x04 \x01(\tR\x06PicUrl\x12\x16\n" +
	"\x06Images\x18\x05 \x01(\tR\x06Images\x12,\n" +
	"\x12level1_category_id\x18\x06 \x01(\rR\x10level1CategoryId\x12,\n" +
	"\x12level2_category_id\x18\a \x01(\rR\x10level2CategoryId\x12,\n" +
	"\x12level3_category_id\x18\b \x01(\rR\x10level3CategoryId\x12\x14\n" +
	"\x05brand\x18\t \x01(\tR\x05brand\x12\x14\n" +
	"\x05stock\x18\n" +
	" \x01(\rR\x05stock\x12\x12\n" +
	"\x04sale\x18\v \x01(\rR\x04sale\x12\x12\n" +
	"\x04tags\x18\f \x01(\tR\x04tags\x12\x1f\n" +
	"\vdetail_info\x18\r \x01(\tR\n" +
	"detailInfo\x12\x12\n" +
	"\x04sort\x18\x0e \x01(\rR\x04sort\"_\n" +
	"\x1eRecommendGoodsInfoListResponse\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.pbentity.GoodsInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"e\n" +
	"\x1cRecommendGoodsInfoGetListRes\x12E\n" +
	"\x04data\x18\x01 \x01(\v21.add_goods_info.v1.RecommendGoodsInfoListResponseR\x04data2\x83\x01\n" +
	"\x12RecommendGoodsInfo\x12m\n" +
	"\aGetList\x12/.add_goods_info.v1.RecommendGoodsInfoGetListReq\x1a/.add_goods_info.v1.RecommendGoodsInfoGetListRes\"\x00BLZJshop-goframe-micro-service-refacotor/app/goods/api/recommend_goods_info/v1b\x06proto3"

var (
	file_recommend_goods_info_v1_recommend_goods_info_proto_rawDescOnce sync.Once
	file_recommend_goods_info_v1_recommend_goods_info_proto_rawDescData []byte
)

func file_recommend_goods_info_v1_recommend_goods_info_proto_rawDescGZIP() []byte {
	file_recommend_goods_info_v1_recommend_goods_info_proto_rawDescOnce.Do(func() {
		file_recommend_goods_info_v1_recommend_goods_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommend_goods_info_v1_recommend_goods_info_proto_rawDesc), len(file_recommend_goods_info_v1_recommend_goods_info_proto_rawDesc)))
	})
	return file_recommend_goods_info_v1_recommend_goods_info_proto_rawDescData
}

var file_recommend_goods_info_v1_recommend_goods_info_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_recommend_goods_info_v1_recommend_goods_info_proto_goTypes = []any{
	(*RecommendGoodsInfoGetListReq)(nil),   // 0: add_goods_info.v1.RecommendGoodsInfoGetListReq
	(*RecommendGoodsItem)(nil),             // 1: add_goods_info.v1.RecommendGoodsItem
	(*RecommendGoodsInfoListResponse)(nil), // 2: add_goods_info.v1.RecommendGoodsInfoListResponse
	(*RecommendGoodsInfoGetListRes)(nil),   // 3: add_goods_info.v1.RecommendGoodsInfoGetListRes
	(*pbentity.GoodsInfo)(nil),             // 4: pbentity.GoodsInfo
}
var file_recommend_goods_info_v1_recommend_goods_info_proto_depIdxs = []int32{
	4, // 0: add_goods_info.v1.RecommendGoodsInfoListResponse.list:type_name -> pbentity.GoodsInfo
	2, // 1: add_goods_info.v1.RecommendGoodsInfoGetListRes.data:type_name -> add_goods_info.v1.RecommendGoodsInfoListResponse
	0, // 2: add_goods_info.v1.RecommendGoodsInfo.GetList:input_type -> add_goods_info.v1.RecommendGoodsInfoGetListReq
	3, // 3: add_goods_info.v1.RecommendGoodsInfo.GetList:output_type -> add_goods_info.v1.RecommendGoodsInfoGetListRes
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_recommend_goods_info_v1_recommend_goods_info_proto_init() }
func file_recommend_goods_info_v1_recommend_goods_info_proto_init() {
	if File_recommend_goods_info_v1_recommend_goods_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommend_goods_info_v1_recommend_goods_info_proto_rawDesc), len(file_recommend_goods_info_v1_recommend_goods_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommend_goods_info_v1_recommend_goods_info_proto_goTypes,
		DependencyIndexes: file_recommend_goods_info_v1_recommend_goods_info_proto_depIdxs,
		MessageInfos:      file_recommend_goods_info_v1_recommend_goods_info_proto_msgTypes,
	}.Build()
	File_recommend_goods_info_v1_recommend_goods_info_proto = out.File
	file_recommend_goods_info_v1_recommend_goods_info_proto_goTypes = nil
	file_recommend_goods_info_v1_recommend_goods_info_proto_depIdxs = nil
}
