// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package interaction

import (
	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
	_ "github.com/gogf/gf/contrib/rpc/grpcx/v2"
	"shop-goframe-micro-service-refacotor/app/gateway-h5/api/interaction"
	goods_info "shop-goframe-micro-service-refacotor/app/goods/api/goods_info/v1"
	collection_info "shop-goframe-micro-service-refacotor/app/interaction/api/collection_info/v1"
	comment_info "shop-goframe-micro-service-refacotor/app/interaction/api/comment_info/v1"
	praise_info "shop-goframe-micro-service-refacotor/app/interaction/api/praise_info/v1"
	"shop-goframe-micro-service-refacotor/utility/middleware"
)

type ControllerV1 struct {
	PraiseInfoClient     praise_info.PraiseInfoClient
	CommentInfoClient    comment_info.CommentInfoClient
	CollectionInfoClient collection_info.CollectionInfoClient
	// collection调用goods服务 添加goods客户端
	GoodsClient goods_info.GoodsInfoClient
}

func NewV1() interaction.IInteractionV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("interaction", grpcx.Client.ChainUnary(
		middleware.GrpcClientTimeout,
	))
	// 添加goods服务的独立连接
	var goods_conn = grpcx.Client.MustNewGrpcClientConn("goods", grpcx.Client.ChainUnary(
		middleware.GrpcClientTimeout,
	))
	return &ControllerV1{
		CollectionInfoClient: collection_info.NewCollectionInfoClient(conn),
		CommentInfoClient:    comment_info.NewCommentInfoClient(conn),
		PraiseInfoClient:     praise_info.NewPraiseInfoClient(conn),
		GoodsClient:          goods_info.NewGoodsInfoClient(goods_conn),
	}
}
