apiVersion: v1
kind: Service
metadata:
  name: goods-service
  labels:
    app: goods-service
spec:
  type: ClusterIP  # 内部服务，只在集群内访问
  ports:
    - name: grpc
      port: 31004  # 与容器端口保持一致
      targetPort: 31004
      protocol: TCP
  selector:
    app: goods-service  # 与Deployment的标签匹配

