// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: pbentity/bargain_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BargainInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                  //
	UserId        int32                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`          //
	GoodsId       int32                  `protobuf:"varint,3,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`        //
	Counts        int32                  `protobuf:"varint,4,opt,name=Counts,proto3" json:"Counts,omitempty"`          //
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty"` //
	UpdatedTime   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdatedTime,proto3" json:"UpdatedTime,omitempty"` //
	DeletedTime   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=DeletedTime,proto3" json:"DeletedTime,omitempty"` //
	ExpiredTime   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ExpiredTime,proto3" json:"ExpiredTime,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainInfo) Reset() {
	*x = BargainInfo{}
	mi := &file_pbentity_bargain_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainInfo) ProtoMessage() {}

func (x *BargainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_bargain_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainInfo.ProtoReflect.Descriptor instead.
func (*BargainInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_bargain_info_proto_rawDescGZIP(), []int{0}
}

func (x *BargainInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BargainInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BargainInfo) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *BargainInfo) GetCounts() int32 {
	if x != nil {
		return x.Counts
	}
	return 0
}

func (x *BargainInfo) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *BargainInfo) GetUpdatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedTime
	}
	return nil
}

func (x *BargainInfo) GetDeletedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedTime
	}
	return nil
}

func (x *BargainInfo) GetExpiredTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredTime
	}
	return nil
}

var File_pbentity_bargain_info_proto protoreflect.FileDescriptor

const file_pbentity_bargain_info_proto_rawDesc = "" +
	"\n" +
	"\x1bpbentity/bargain_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x02\n" +
	"\vBargainInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x05R\x06UserId\x12\x18\n" +
	"\aGoodsId\x18\x03 \x01(\x05R\aGoodsId\x12\x16\n" +
	"\x06Counts\x18\x04 \x01(\x05R\x06Counts\x12<\n" +
	"\vCreatedTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vCreatedTime\x12<\n" +
	"\vUpdatedTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vUpdatedTime\x12<\n" +
	"\vDeletedTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vDeletedTime\x12<\n" +
	"\vExpiredTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vExpiredTimeB=Z;shop-goframe-micro-service-refacotor/app/goods/api/pbentityb\x06proto3"

var (
	file_pbentity_bargain_info_proto_rawDescOnce sync.Once
	file_pbentity_bargain_info_proto_rawDescData []byte
)

func file_pbentity_bargain_info_proto_rawDescGZIP() []byte {
	file_pbentity_bargain_info_proto_rawDescOnce.Do(func() {
		file_pbentity_bargain_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_bargain_info_proto_rawDesc), len(file_pbentity_bargain_info_proto_rawDesc)))
	})
	return file_pbentity_bargain_info_proto_rawDescData
}

var file_pbentity_bargain_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_bargain_info_proto_goTypes = []any{
	(*BargainInfo)(nil),           // 0: pbentity.BargainInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_bargain_info_proto_depIdxs = []int32{
	1, // 0: pbentity.BargainInfo.CreatedTime:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.BargainInfo.UpdatedTime:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.BargainInfo.DeletedTime:type_name -> google.protobuf.Timestamp
	1, // 3: pbentity.BargainInfo.ExpiredTime:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pbentity_bargain_info_proto_init() }
func file_pbentity_bargain_info_proto_init() {
	if File_pbentity_bargain_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_bargain_info_proto_rawDesc), len(file_pbentity_bargain_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_bargain_info_proto_goTypes,
		DependencyIndexes: file_pbentity_bargain_info_proto_depIdxs,
		MessageInfos:      file_pbentity_bargain_info_proto_msgTypes,
	}.Build()
	File_pbentity_bargain_info_proto = out.File
	file_pbentity_bargain_info_proto_goTypes = nil
	file_pbentity_bargain_info_proto_depIdxs = nil
}
