// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: cart_info/v1/cart_info.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CartInfo_GetList_FullMethodName          = "/cart_info.v1.cart_info/GetList"
	CartInfo_Create_FullMethodName           = "/cart_info.v1.cart_info/Create"
	CartInfo_Delete_FullMethodName           = "/cart_info.v1.cart_info/Delete"
	CartInfo_Put_FullMethodName              = "/cart_info.v1.cart_info/Put"
	CartInfo_GetSelectedItems_FullMethodName = "/cart_info.v1.cart_info/GetSelectedItems"
)

// CartInfoClient is the client API for CartInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartInfoClient interface {
	GetList(ctx context.Context, in *CartInfoGetListReq, opts ...grpc.CallOption) (*CartInfoGetListRes, error)
	Create(ctx context.Context, in *CartInfoCreateReq, opts ...grpc.CallOption) (*CartInfoCreateRes, error)
	Delete(ctx context.Context, in *CartInfoDeleteReq, opts ...grpc.CallOption) (*CartInfoDeleteRes, error)
	Put(ctx context.Context, in *CartInfoPutReq, opts ...grpc.CallOption) (*CartInfoPutRes, error)
	GetSelectedItems(ctx context.Context, in *CartInfoGetSelectedItemsReq, opts ...grpc.CallOption) (*CartInfoGetSelectedItemsRes, error)
}

type cartInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewCartInfoClient(cc grpc.ClientConnInterface) CartInfoClient {
	return &cartInfoClient{cc}
}

func (c *cartInfoClient) GetList(ctx context.Context, in *CartInfoGetListReq, opts ...grpc.CallOption) (*CartInfoGetListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartInfoGetListRes)
	err := c.cc.Invoke(ctx, CartInfo_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartInfoClient) Create(ctx context.Context, in *CartInfoCreateReq, opts ...grpc.CallOption) (*CartInfoCreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartInfoCreateRes)
	err := c.cc.Invoke(ctx, CartInfo_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartInfoClient) Delete(ctx context.Context, in *CartInfoDeleteReq, opts ...grpc.CallOption) (*CartInfoDeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartInfoDeleteRes)
	err := c.cc.Invoke(ctx, CartInfo_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartInfoClient) Put(ctx context.Context, in *CartInfoPutReq, opts ...grpc.CallOption) (*CartInfoPutRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartInfoPutRes)
	err := c.cc.Invoke(ctx, CartInfo_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartInfoClient) GetSelectedItems(ctx context.Context, in *CartInfoGetSelectedItemsReq, opts ...grpc.CallOption) (*CartInfoGetSelectedItemsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartInfoGetSelectedItemsRes)
	err := c.cc.Invoke(ctx, CartInfo_GetSelectedItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartInfoServer is the server API for CartInfo service.
// All implementations must embed UnimplementedCartInfoServer
// for forward compatibility.
type CartInfoServer interface {
	GetList(context.Context, *CartInfoGetListReq) (*CartInfoGetListRes, error)
	Create(context.Context, *CartInfoCreateReq) (*CartInfoCreateRes, error)
	Delete(context.Context, *CartInfoDeleteReq) (*CartInfoDeleteRes, error)
	Put(context.Context, *CartInfoPutReq) (*CartInfoPutRes, error)
	GetSelectedItems(context.Context, *CartInfoGetSelectedItemsReq) (*CartInfoGetSelectedItemsRes, error)
	mustEmbedUnimplementedCartInfoServer()
}

// UnimplementedCartInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCartInfoServer struct{}

func (UnimplementedCartInfoServer) GetList(context.Context, *CartInfoGetListReq) (*CartInfoGetListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedCartInfoServer) Create(context.Context, *CartInfoCreateReq) (*CartInfoCreateRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCartInfoServer) Delete(context.Context, *CartInfoDeleteReq) (*CartInfoDeleteRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCartInfoServer) Put(context.Context, *CartInfoPutReq) (*CartInfoPutRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedCartInfoServer) GetSelectedItems(context.Context, *CartInfoGetSelectedItemsReq) (*CartInfoGetSelectedItemsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSelectedItems not implemented")
}
func (UnimplementedCartInfoServer) mustEmbedUnimplementedCartInfoServer() {}
func (UnimplementedCartInfoServer) testEmbeddedByValue()                  {}

// UnsafeCartInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartInfoServer will
// result in compilation errors.
type UnsafeCartInfoServer interface {
	mustEmbedUnimplementedCartInfoServer()
}

func RegisterCartInfoServer(s grpc.ServiceRegistrar, srv CartInfoServer) {
	// If the following call panics, it indicates UnimplementedCartInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CartInfo_ServiceDesc, srv)
}

func _CartInfo_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartInfoGetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartInfoServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartInfo_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartInfoServer).GetList(ctx, req.(*CartInfoGetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartInfo_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartInfoCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartInfoServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartInfo_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartInfoServer).Create(ctx, req.(*CartInfoCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartInfo_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartInfoDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartInfoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartInfo_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartInfoServer).Delete(ctx, req.(*CartInfoDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartInfo_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartInfoPutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartInfoServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartInfo_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartInfoServer).Put(ctx, req.(*CartInfoPutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartInfo_GetSelectedItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartInfoGetSelectedItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartInfoServer).GetSelectedItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartInfo_GetSelectedItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartInfoServer).GetSelectedItems(ctx, req.(*CartInfoGetSelectedItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CartInfo_ServiceDesc is the grpc.ServiceDesc for CartInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cart_info.v1.cart_info",
	HandlerType: (*CartInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _CartInfo_GetList_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _CartInfo_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CartInfo_Delete_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _CartInfo_Put_Handler,
		},
		{
			MethodName: "GetSelectedItems",
			Handler:    _CartInfo_GetSelectedItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart_info/v1/cart_info.proto",
}
