// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: order_info/v1/order_info.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderInfo_Create_FullMethodName         = "/order_info.v1.order_info/Create"
	OrderInfo_CreateFromCart_FullMethodName = "/order_info.v1.order_info/CreateFromCart"
	OrderInfo_GetDetail_FullMethodName      = "/order_info.v1.order_info/GetDetail"
	OrderInfo_GetList_FullMethodName        = "/order_info.v1.order_info/GetList"
	OrderInfo_GetCount_FullMethodName       = "/order_info.v1.order_info/GetCount"
	OrderInfo_Payment_FullMethodName        = "/order_info.v1.order_info/Payment"
	OrderInfo_Notify_FullMethodName         = "/order_info.v1.order_info/Notify"
	OrderInfo_CancelOrder_FullMethodName    = "/order_info.v1.order_info/CancelOrder"
	OrderInfo_Preview_FullMethodName        = "/order_info.v1.order_info/Preview"
	OrderInfo_Compensate_FullMethodName     = "/order_info.v1.order_info/Compensate"
	OrderInfo_CancelTimeout_FullMethodName  = "/order_info.v1.order_info/CancelTimeout"
)

// OrderInfoClient is the client API for OrderInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderInfoClient interface {
	Create(ctx context.Context, in *OrderInfoCreateReq, opts ...grpc.CallOption) (*OrderInfoCreateRes, error)
	CreateFromCart(ctx context.Context, in *OrderInfoCreateFromCartReq, opts ...grpc.CallOption) (*OrderInfoCreateRes, error)
	GetDetail(ctx context.Context, in *OrderInfoGetDetailReq, opts ...grpc.CallOption) (*OrderInfoGetDetailRes, error)
	GetList(ctx context.Context, in *OrderInfoGetListReq, opts ...grpc.CallOption) (*OrderInfoGetListRes, error)
	GetCount(ctx context.Context, in *OrderInfoGetCountReq, opts ...grpc.CallOption) (*OrderInfoGetCountRes, error)
	Payment(ctx context.Context, in *PaymentReq, opts ...grpc.CallOption) (*PaymentRes, error)
	Notify(ctx context.Context, in *NotifyReq, opts ...grpc.CallOption) (*NotifyRes, error)
	CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderRes, error)
	Preview(ctx context.Context, in *OrderInfoPreviewReq, opts ...grpc.CallOption) (*OrderInfoPreviewRes, error)
	Compensate(ctx context.Context, in *OrderInfoCompensateReq, opts ...grpc.CallOption) (*OrderInfoCompensateRes, error)
	CancelTimeout(ctx context.Context, in *CancelTimeoutPendingOrdersReq, opts ...grpc.CallOption) (*CancelTimeoutPendingOrdersRes, error)
}

type orderInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderInfoClient(cc grpc.ClientConnInterface) OrderInfoClient {
	return &orderInfoClient{cc}
}

func (c *orderInfoClient) Create(ctx context.Context, in *OrderInfoCreateReq, opts ...grpc.CallOption) (*OrderInfoCreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfoCreateRes)
	err := c.cc.Invoke(ctx, OrderInfo_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoClient) CreateFromCart(ctx context.Context, in *OrderInfoCreateFromCartReq, opts ...grpc.CallOption) (*OrderInfoCreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfoCreateRes)
	err := c.cc.Invoke(ctx, OrderInfo_CreateFromCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoClient) GetDetail(ctx context.Context, in *OrderInfoGetDetailReq, opts ...grpc.CallOption) (*OrderInfoGetDetailRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfoGetDetailRes)
	err := c.cc.Invoke(ctx, OrderInfo_GetDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoClient) GetList(ctx context.Context, in *OrderInfoGetListReq, opts ...grpc.CallOption) (*OrderInfoGetListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfoGetListRes)
	err := c.cc.Invoke(ctx, OrderInfo_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoClient) GetCount(ctx context.Context, in *OrderInfoGetCountReq, opts ...grpc.CallOption) (*OrderInfoGetCountRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfoGetCountRes)
	err := c.cc.Invoke(ctx, OrderInfo_GetCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoClient) Payment(ctx context.Context, in *PaymentReq, opts ...grpc.CallOption) (*PaymentRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentRes)
	err := c.cc.Invoke(ctx, OrderInfo_Payment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoClient) Notify(ctx context.Context, in *NotifyReq, opts ...grpc.CallOption) (*NotifyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyRes)
	err := c.cc.Invoke(ctx, OrderInfo_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoClient) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderRes)
	err := c.cc.Invoke(ctx, OrderInfo_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoClient) Preview(ctx context.Context, in *OrderInfoPreviewReq, opts ...grpc.CallOption) (*OrderInfoPreviewRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfoPreviewRes)
	err := c.cc.Invoke(ctx, OrderInfo_Preview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoClient) Compensate(ctx context.Context, in *OrderInfoCompensateReq, opts ...grpc.CallOption) (*OrderInfoCompensateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfoCompensateRes)
	err := c.cc.Invoke(ctx, OrderInfo_Compensate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoClient) CancelTimeout(ctx context.Context, in *CancelTimeoutPendingOrdersReq, opts ...grpc.CallOption) (*CancelTimeoutPendingOrdersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTimeoutPendingOrdersRes)
	err := c.cc.Invoke(ctx, OrderInfo_CancelTimeout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderInfoServer is the server API for OrderInfo service.
// All implementations must embed UnimplementedOrderInfoServer
// for forward compatibility.
type OrderInfoServer interface {
	Create(context.Context, *OrderInfoCreateReq) (*OrderInfoCreateRes, error)
	CreateFromCart(context.Context, *OrderInfoCreateFromCartReq) (*OrderInfoCreateRes, error)
	GetDetail(context.Context, *OrderInfoGetDetailReq) (*OrderInfoGetDetailRes, error)
	GetList(context.Context, *OrderInfoGetListReq) (*OrderInfoGetListRes, error)
	GetCount(context.Context, *OrderInfoGetCountReq) (*OrderInfoGetCountRes, error)
	Payment(context.Context, *PaymentReq) (*PaymentRes, error)
	Notify(context.Context, *NotifyReq) (*NotifyRes, error)
	CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderRes, error)
	Preview(context.Context, *OrderInfoPreviewReq) (*OrderInfoPreviewRes, error)
	Compensate(context.Context, *OrderInfoCompensateReq) (*OrderInfoCompensateRes, error)
	CancelTimeout(context.Context, *CancelTimeoutPendingOrdersReq) (*CancelTimeoutPendingOrdersRes, error)
	mustEmbedUnimplementedOrderInfoServer()
}

// UnimplementedOrderInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderInfoServer struct{}

func (UnimplementedOrderInfoServer) Create(context.Context, *OrderInfoCreateReq) (*OrderInfoCreateRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedOrderInfoServer) CreateFromCart(context.Context, *OrderInfoCreateFromCartReq) (*OrderInfoCreateRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFromCart not implemented")
}
func (UnimplementedOrderInfoServer) GetDetail(context.Context, *OrderInfoGetDetailReq) (*OrderInfoGetDetailRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetail not implemented")
}
func (UnimplementedOrderInfoServer) GetList(context.Context, *OrderInfoGetListReq) (*OrderInfoGetListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedOrderInfoServer) GetCount(context.Context, *OrderInfoGetCountReq) (*OrderInfoGetCountRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCount not implemented")
}
func (UnimplementedOrderInfoServer) Payment(context.Context, *PaymentReq) (*PaymentRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Payment not implemented")
}
func (UnimplementedOrderInfoServer) Notify(context.Context, *NotifyReq) (*NotifyRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedOrderInfoServer) CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrderInfoServer) Preview(context.Context, *OrderInfoPreviewReq) (*OrderInfoPreviewRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Preview not implemented")
}
func (UnimplementedOrderInfoServer) Compensate(context.Context, *OrderInfoCompensateReq) (*OrderInfoCompensateRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Compensate not implemented")
}
func (UnimplementedOrderInfoServer) CancelTimeout(context.Context, *CancelTimeoutPendingOrdersReq) (*CancelTimeoutPendingOrdersRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTimeout not implemented")
}
func (UnimplementedOrderInfoServer) mustEmbedUnimplementedOrderInfoServer() {}
func (UnimplementedOrderInfoServer) testEmbeddedByValue()                   {}

// UnsafeOrderInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderInfoServer will
// result in compilation errors.
type UnsafeOrderInfoServer interface {
	mustEmbedUnimplementedOrderInfoServer()
}

func RegisterOrderInfoServer(s grpc.ServiceRegistrar, srv OrderInfoServer) {
	// If the following call panics, it indicates UnimplementedOrderInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderInfo_ServiceDesc, srv)
}

func _OrderInfo_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).Create(ctx, req.(*OrderInfoCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfo_CreateFromCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoCreateFromCartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).CreateFromCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_CreateFromCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).CreateFromCart(ctx, req.(*OrderInfoCreateFromCartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfo_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoGetDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_GetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).GetDetail(ctx, req.(*OrderInfoGetDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfo_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoGetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).GetList(ctx, req.(*OrderInfoGetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfo_GetCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoGetCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).GetCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_GetCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).GetCount(ctx, req.(*OrderInfoGetCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfo_Payment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).Payment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_Payment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).Payment(ctx, req.(*PaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfo_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).Notify(ctx, req.(*NotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfo_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).CancelOrder(ctx, req.(*CancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfo_Preview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoPreviewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).Preview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_Preview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).Preview(ctx, req.(*OrderInfoPreviewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfo_Compensate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoCompensateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).Compensate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_Compensate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).Compensate(ctx, req.(*OrderInfoCompensateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfo_CancelTimeout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTimeoutPendingOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).CancelTimeout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_CancelTimeout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).CancelTimeout(ctx, req.(*CancelTimeoutPendingOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderInfo_ServiceDesc is the grpc.ServiceDesc for OrderInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order_info.v1.order_info",
	HandlerType: (*OrderInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OrderInfo_Create_Handler,
		},
		{
			MethodName: "CreateFromCart",
			Handler:    _OrderInfo_CreateFromCart_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _OrderInfo_GetDetail_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _OrderInfo_GetList_Handler,
		},
		{
			MethodName: "GetCount",
			Handler:    _OrderInfo_GetCount_Handler,
		},
		{
			MethodName: "Payment",
			Handler:    _OrderInfo_Payment_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _OrderInfo_Notify_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrderInfo_CancelOrder_Handler,
		},
		{
			MethodName: "Preview",
			Handler:    _OrderInfo_Preview_Handler,
		},
		{
			MethodName: "Compensate",
			Handler:    _OrderInfo_Compensate_Handler,
		},
		{
			MethodName: "CancelTimeout",
			Handler:    _OrderInfo_CancelTimeout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_info/v1/order_info.proto",
}
