// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: order_info/v1/order_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service-refacotor/app/order/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建订单请求
type OrderInfoCreateReq struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Price       uint32                 `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty" dc:"订单金额"`                                  // 订单金额
	CouponPrice uint32                 `protobuf:"varint,2,opt,name=coupon_price,json=couponPrice,proto3" json:"coupon_price,omitempty" dc:"优惠券金额"`  // 优惠券金额
	ActualPrice uint32                 `protobuf:"varint,3,opt,name=actual_price,json=actualPrice,proto3" json:"actual_price,omitempty" dc:"实际支付金额"` // 实际支付金额
	// string consignee_name = 4;             // 收货人姓名
	ConsigneePhone string `protobuf:"bytes,5,opt,name=consignee_phone,json=consigneePhone,proto3" json:"consignee_phone,omitempty" dc:"string consignee_name = 4;             // 收货人姓名收货人手机号"` // 收货人手机号
	// string consignee_address = 6;          // 收货人详细地址
	Remark         string            `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty" dc:"string consignee_address = 6;          // 收货人详细地址备注"` // 备注
	OrderGoodsInfo []*OrderGoodsItem `protobuf:"bytes,8,rep,name=order_goods_info,json=orderGoodsInfo,proto3" json:"order_goods_info,omitempty" dc:"订单商品信息"`      // 订单商品信息
	UserId         uint32            `protobuf:"varint,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" dc:"用户id"`                                 // 用户id
	CouponId       uint32            `protobuf:"varint,10,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty" dc:"优惠券id"`                         // 优惠券id
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderInfoCreateReq) Reset() {
	*x = OrderInfoCreateReq{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoCreateReq) ProtoMessage() {}

func (x *OrderInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoCreateReq.ProtoReflect.Descriptor instead.
func (*OrderInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{0}
}

func (x *OrderInfoCreateReq) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderInfoCreateReq) GetCouponPrice() uint32 {
	if x != nil {
		return x.CouponPrice
	}
	return 0
}

func (x *OrderInfoCreateReq) GetActualPrice() uint32 {
	if x != nil {
		return x.ActualPrice
	}
	return 0
}

func (x *OrderInfoCreateReq) GetConsigneePhone() string {
	if x != nil {
		return x.ConsigneePhone
	}
	return ""
}

func (x *OrderInfoCreateReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderInfoCreateReq) GetOrderGoodsInfo() []*OrderGoodsItem {
	if x != nil {
		return x.OrderGoodsInfo
	}
	return nil
}

func (x *OrderInfoCreateReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfoCreateReq) GetCouponId() uint32 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

// 订单商品项
type OrderGoodsItem struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GoodsId uint32                 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty" dc:"商品id"` // 商品id
	// uint32 goods_options_id = 2;    // 商品规格id
	Count         uint32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty" dc:"uint32 goods_options_id = 2;    // 商品规格id商品数量"` // 商品数量
	Remark        string `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty" dc:"备注"`                                           // 备注
	Price         uint32 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty" dc:"商品金额"`                                          // 商品金额
	CouponPrice   uint32 `protobuf:"varint,6,opt,name=coupon_price,json=couponPrice,proto3" json:"coupon_price,omitempty" dc:"商品优惠券金额"`        // 商品优惠券金额
	ActualPrice   uint32 `protobuf:"varint,7,opt,name=actual_price,json=actualPrice,proto3" json:"actual_price,omitempty" dc:"商品实际支付金额"`       // 商品实际支付金额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderGoodsItem) Reset() {
	*x = OrderGoodsItem{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGoodsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGoodsItem) ProtoMessage() {}

func (x *OrderGoodsItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGoodsItem.ProtoReflect.Descriptor instead.
func (*OrderGoodsItem) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{1}
}

func (x *OrderGoodsItem) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *OrderGoodsItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OrderGoodsItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderGoodsItem) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderGoodsItem) GetCouponPrice() uint32 {
	if x != nil {
		return x.CouponPrice
	}
	return 0
}

func (x *OrderGoodsItem) GetActualPrice() uint32 {
	if x != nil {
		return x.ActualPrice
	}
	return 0
}

// 创建订单响应
type OrderInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoCreateRes) Reset() {
	*x = OrderInfoCreateRes{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoCreateRes) ProtoMessage() {}

func (x *OrderInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoCreateRes.ProtoReflect.Descriptor instead.
func (*OrderInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{2}
}

func (x *OrderInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfoCreateRes) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

// 根据ID查询请求
type OrderInfoGetDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoGetDetailReq) Reset() {
	*x = OrderInfoGetDetailReq{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoGetDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoGetDetailReq) ProtoMessage() {}

func (x *OrderInfoGetDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoGetDetailReq.ProtoReflect.Descriptor instead.
func (*OrderInfoGetDetailReq) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{3}
}

func (x *OrderInfoGetDetailReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 根据ID查询响应
type OrderInfoGetDetailRes struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	OrderInfo       *pbentity.OrderInfo        `protobuf:"bytes,1,opt,name=order_info,json=orderInfo,proto3" json:"order_info,omitempty"`
	OrderGoodsInfos []*pbentity.OrderGoodsInfo `protobuf:"bytes,2,rep,name=order_goods_infos,json=orderGoodsInfos,proto3" json:"order_goods_infos,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderInfoGetDetailRes) Reset() {
	*x = OrderInfoGetDetailRes{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoGetDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoGetDetailRes) ProtoMessage() {}

func (x *OrderInfoGetDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoGetDetailRes.ProtoReflect.Descriptor instead.
func (*OrderInfoGetDetailRes) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{4}
}

func (x *OrderInfoGetDetailRes) GetOrderInfo() *pbentity.OrderInfo {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

func (x *OrderInfoGetDetailRes) GetOrderGoodsInfos() []*pbentity.OrderGoodsInfo {
	if x != nil {
		return x.OrderGoodsInfos
	}
	return nil
}

// =======分页查询请求 V2版本 模仿淘宝 order服务内改动 ========
type OrderInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" dc:"user_id 用户id 不确定该不该有 先写"`           // user_id 用户id 不确定该不该有 先写
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty" dc:"分页号码，默认1"`                                            // 分页号码，默认1
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty" dc:"分页数量，最大50"`                                           // 分页数量，最大50
	Status        uint32                 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty" dc:"订单支付状态 1待支付 2已支付待发货 3已发货 4已收货待评价 5已评价 6待确认 7已取消"` //订单支付状态 1待支付 2已支付待发货 3已发货 4已收货待评价 5已评价 6待确认 7已取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoGetListReq) Reset() {
	*x = OrderInfoGetListReq{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoGetListReq) ProtoMessage() {}

func (x *OrderInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoGetListReq.ProtoReflect.Descriptor instead.
func (*OrderInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{5}
}

func (x *OrderInfoGetListReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *OrderInfoGetListReq) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 响应专用结构体
type OrderListInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"order_info的 id字段 orderid"`                    //order_info的 id字段 orderid
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty" dc:"用户id，调接口测试用"`                         //用户id，调接口测试用
	Number        string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty" dc:"订单编号"`                                 //订单编号
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty" dc:"支付状态"`                                //支付状态
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty" dc:"订单总金额"`                                 //订单总金额
	ActualPrice   int32                  `protobuf:"varint,6,opt,name=actual_price,json=actualPrice,proto3" json:"actual_price,omitempty" dc:"订单实际金额"` //  订单实际金额
	GoodsInfo     []*OrderListGoodsInfo  `protobuf:"bytes,7,rep,name=goods_info,json=goodsInfo,proto3" json:"goods_info,omitempty" dc:"关联的订单商品信息"`     // 关联的订单商品信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListInfo) Reset() {
	*x = OrderListInfo{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListInfo) ProtoMessage() {}

func (x *OrderListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListInfo.ProtoReflect.Descriptor instead.
func (*OrderListInfo) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{6}
}

func (x *OrderListInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderListInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderListInfo) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *OrderListInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderListInfo) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderListInfo) GetActualPrice() int32 {
	if x != nil {
		return x.ActualPrice
	}
	return 0
}

func (x *OrderListInfo) GetGoodsInfo() []*OrderListGoodsInfo {
	if x != nil {
		return x.GoodsInfo
	}
	return nil
}

// 响应专供结构体 goodsInfo相关
type OrderListGoodsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListGoodsInfo) Reset() {
	*x = OrderListGoodsInfo{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListGoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListGoodsInfo) ProtoMessage() {}

func (x *OrderListGoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListGoodsInfo.ProtoReflect.Descriptor instead.
func (*OrderListGoodsInfo) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{7}
}

func (x *OrderListGoodsInfo) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *OrderListGoodsInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 分页数据响应 v2 版本
type OrderInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderListInfo       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty" dc:"总数量"`     // 总数量
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty" dc:"分页号码，默认1"`  // 分页号码，默认1
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty" dc:"分页数量，最大50"` // 分页数量，最大50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoListResponse) Reset() {
	*x = OrderInfoListResponse{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoListResponse) ProtoMessage() {}

func (x *OrderInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoListResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoListResponse) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{8}
}

func (x *OrderInfoListResponse) GetList() []*OrderListInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *OrderInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 分页查询响应
type OrderInfoGetListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *OrderInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoGetListRes) Reset() {
	*x = OrderInfoGetListRes{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoGetListRes) ProtoMessage() {}

func (x *OrderInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoGetListRes.ProtoReflect.Descriptor instead.
func (*OrderInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{9}
}

func (x *OrderInfoGetListRes) GetData() *OrderInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// 支付请求体
type PaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty" dc:"用户登录凭证（微信 openid）"` // 用户登录凭证（微信 openid）
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty" dc:"金额，单位为分"`          // 金额，单位为分
	Number        string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty" dc:"订单Id"`              // 订单Id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentReq) Reset() {
	*x = PaymentReq{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReq) ProtoMessage() {}

func (x *PaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReq.ProtoReflect.Descriptor instead.
func (*PaymentReq) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{10}
}

func (x *PaymentReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *PaymentReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentReq) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

// 支付响应体
type PaymentRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeStamp     string                 `protobuf:"bytes,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty" dc:"时间戳，单位秒，字符串格式"`                         // 时间戳，单位秒，字符串格式
	NonceStr      string                 `protobuf:"bytes,2,opt,name=nonceStr,proto3" json:"nonceStr,omitempty" dc:"随机字符串，防重放攻击"`                             // 随机字符串，防重放攻击
	Package       string                 `protobuf:"bytes,3,opt,name=package,proto3" json:"package,omitempty" dc:"统一下单接口返回的预支付交易会话标识，格式为 prepay_id=***"`      // 统一下单接口返回的预支付交易会话标识，格式为 prepay_id=***
	SignType      string                 `protobuf:"bytes,4,opt,name=signType,proto3" json:"signType,omitempty" dc:"签名类型，微信支付 v3 常用 RSA"`                     // 签名类型，微信支付 v3 常用 RSA
	PaySign       string                 `protobuf:"bytes,5,opt,name=paySign,proto3" json:"paySign,omitempty" dc:"支付签名，商户后端使用私钥生成"`                           // 支付签名，商户后端使用私钥生成
	OutTradeNo    string                 `protobuf:"bytes,6,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty" dc:"商户订单号，用于后续查单、退款"` // 商户订单号，用于后续查单、退款
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRes) Reset() {
	*x = PaymentRes{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRes) ProtoMessage() {}

func (x *PaymentRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRes.ProtoReflect.Descriptor instead.
func (*PaymentRes) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{11}
}

func (x *PaymentRes) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *PaymentRes) GetNonceStr() string {
	if x != nil {
		return x.NonceStr
	}
	return ""
}

func (x *PaymentRes) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *PaymentRes) GetSignType() string {
	if x != nil {
		return x.SignType
	}
	return ""
}

func (x *PaymentRes) GetPaySign() string {
	if x != nil {
		return x.PaySign
	}
	return ""
}

func (x *PaymentRes) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

// 回调请求体
type NotifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawBody       string                 `protobuf:"bytes,1,opt,name=raw_body,json=rawBody,proto3" json:"raw_body,omitempty" dc:"微信原始回调 body（JSON）"`                                                                                                                                         // 微信原始回调 body（JSON）
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" dc:"回调的 HTTP headers (Wechatpay-Signature, Wechatpay-Timestamp, Wechatpay-Nonce, Wechatpay-Serial)"` // 回调的 HTTP headers (Wechatpay-Signature, Wechatpay-Timestamp, Wechatpay-Nonce, Wechatpay-Serial)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyReq) Reset() {
	*x = NotifyReq{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReq) ProtoMessage() {}

func (x *NotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReq.ProtoReflect.Descriptor instead.
func (*NotifyReq) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{12}
}

func (x *NotifyReq) GetRawBody() string {
	if x != nil {
		return x.RawBody
	}
	return ""
}

func (x *NotifyReq) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// 回调响应体
type NotifyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty" dc:"SUCCESS / FAIL"` // SUCCESS / FAIL
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" dc:"返回信息"`     // 返回信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRes) Reset() {
	*x = NotifyRes{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRes) ProtoMessage() {}

func (x *NotifyRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRes.ProtoReflect.Descriptor instead.
func (*NotifyRes) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{13}
}

func (x *NotifyRes) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *NotifyRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_order_info_v1_order_info_proto protoreflect.FileDescriptor

const file_order_info_v1_order_info_proto_rawDesc = "" +
	"\n" +
	"\x1eorder_info/v1/order_info.proto\x12\rorder_info.v1\x1a\x19pbentity/order_info.proto\x1a\x1fpbentity/order_goods_info.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x02\n" +
	"\x12OrderInfoCreateReq\x12\x14\n" +
	"\x05price\x18\x01 \x01(\rR\x05price\x12!\n" +
	"\fcoupon_price\x18\x02 \x01(\rR\vcouponPrice\x12!\n" +
	"\factual_price\x18\x03 \x01(\rR\vactualPrice\x12'\n" +
	"\x0fconsignee_phone\x18\x05 \x01(\tR\x0econsigneePhone\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x12G\n" +
	"\x10order_goods_info\x18\b \x03(\v2\x1d.order_info.v1.OrderGoodsItemR\x0eorderGoodsInfo\x12\x17\n" +
	"\auser_id\x18\t \x01(\rR\x06userId\x12\x1b\n" +
	"\tcoupon_id\x18\n" +
	" \x01(\rR\bcouponId\"\xb5\x01\n" +
	"\x0eOrderGoodsItem\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\rR\agoodsId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x14\n" +
	"\x05price\x18\x05 \x01(\rR\x05price\x12!\n" +
	"\fcoupon_price\x18\x06 \x01(\rR\vcouponPrice\x12!\n" +
	"\factual_price\x18\a \x01(\rR\vactualPrice\"<\n" +
	"\x12OrderInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\"'\n" +
	"\x15OrderInfoGetDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x91\x01\n" +
	"\x15OrderInfoGetDetailRes\x122\n" +
	"\n" +
	"order_info\x18\x01 \x01(\v2\x13.pbentity.OrderInfoR\torderInfo\x12D\n" +
	"\x11order_goods_infos\x18\x02 \x03(\v2\x18.pbentity.OrderGoodsInfoR\x0forderGoodsInfos\"n\n" +
	"\x13OrderInfoGetListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x16\n" +
	"\x06status\x18\x04 \x01(\rR\x06status\"\xe2\x01\n" +
	"\rOrderListInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12!\n" +
	"\factual_price\x18\x06 \x01(\x05R\vactualPrice\x12@\n" +
	"\n" +
	"goods_info\x18\a \x03(\v2!.order_info.v1.OrderListGoodsInfoR\tgoodsInfo\"E\n" +
	"\x12OrderListGoodsInfo\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x05R\agoodsId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x87\x01\n" +
	"\x15OrderInfoListResponse\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.order_info.v1.OrderListInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\"O\n" +
	"\x13OrderInfoGetListRes\x128\n" +
	"\x04data\x18\x01 \x01(\v2$.order_info.v1.OrderInfoListResponseR\x04data\"T\n" +
	"\n" +
	"PaymentReq\x12\x16\n" +
	"\x06openId\x18\x01 \x01(\tR\x06openId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\"\xb8\x01\n" +
	"\n" +
	"PaymentRes\x12\x1c\n" +
	"\ttimeStamp\x18\x01 \x01(\tR\ttimeStamp\x12\x1a\n" +
	"\bnonceStr\x18\x02 \x01(\tR\bnonceStr\x12\x18\n" +
	"\apackage\x18\x03 \x01(\tR\apackage\x12\x1a\n" +
	"\bsignType\x18\x04 \x01(\tR\bsignType\x12\x18\n" +
	"\apaySign\x18\x05 \x01(\tR\apaySign\x12 \n" +
	"\fout_trade_no\x18\x06 \x01(\tR\n" +
	"outTradeNo\"\xa3\x01\n" +
	"\tNotifyReq\x12\x19\n" +
	"\braw_body\x18\x01 \x01(\tR\arawBody\x12?\n" +
	"\aheaders\x18\x02 \x03(\v2%.order_info.v1.NotifyReq.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\tNotifyRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x91\x03\n" +
	"\n" +
	"order_info\x12P\n" +
	"\x06Create\x12!.order_info.v1.OrderInfoCreateReq\x1a!.order_info.v1.OrderInfoCreateRes\"\x00\x12Y\n" +
	"\tGetDetail\x12$.order_info.v1.OrderInfoGetDetailReq\x1a$.order_info.v1.OrderInfoGetDetailRes\"\x00\x12S\n" +
	"\aGetList\x12\".order_info.v1.OrderInfoGetListReq\x1a\".order_info.v1.OrderInfoGetListRes\"\x00\x12A\n" +
	"\aPayment\x12\x19.order_info.v1.PaymentReq\x1a\x19.order_info.v1.PaymentRes\"\x00\x12>\n" +
	"\x06Notify\x12\x18.order_info.v1.NotifyReq\x1a\x18.order_info.v1.NotifyRes\"\x00BBZ@shop-goframe-micro-service-refacotor/app/order/api/order_info/v1b\x06proto3"

var (
	file_order_info_v1_order_info_proto_rawDescOnce sync.Once
	file_order_info_v1_order_info_proto_rawDescData []byte
)

func file_order_info_v1_order_info_proto_rawDescGZIP() []byte {
	file_order_info_v1_order_info_proto_rawDescOnce.Do(func() {
		file_order_info_v1_order_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_info_v1_order_info_proto_rawDesc), len(file_order_info_v1_order_info_proto_rawDesc)))
	})
	return file_order_info_v1_order_info_proto_rawDescData
}

var file_order_info_v1_order_info_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_order_info_v1_order_info_proto_goTypes = []any{
	(*OrderInfoCreateReq)(nil),      // 0: order_info.v1.OrderInfoCreateReq
	(*OrderGoodsItem)(nil),          // 1: order_info.v1.OrderGoodsItem
	(*OrderInfoCreateRes)(nil),      // 2: order_info.v1.OrderInfoCreateRes
	(*OrderInfoGetDetailReq)(nil),   // 3: order_info.v1.OrderInfoGetDetailReq
	(*OrderInfoGetDetailRes)(nil),   // 4: order_info.v1.OrderInfoGetDetailRes
	(*OrderInfoGetListReq)(nil),     // 5: order_info.v1.OrderInfoGetListReq
	(*OrderListInfo)(nil),           // 6: order_info.v1.OrderListInfo
	(*OrderListGoodsInfo)(nil),      // 7: order_info.v1.OrderListGoodsInfo
	(*OrderInfoListResponse)(nil),   // 8: order_info.v1.OrderInfoListResponse
	(*OrderInfoGetListRes)(nil),     // 9: order_info.v1.OrderInfoGetListRes
	(*PaymentReq)(nil),              // 10: order_info.v1.PaymentReq
	(*PaymentRes)(nil),              // 11: order_info.v1.PaymentRes
	(*NotifyReq)(nil),               // 12: order_info.v1.NotifyReq
	(*NotifyRes)(nil),               // 13: order_info.v1.NotifyRes
	nil,                             // 14: order_info.v1.NotifyReq.HeadersEntry
	(*pbentity.OrderInfo)(nil),      // 15: pbentity.OrderInfo
	(*pbentity.OrderGoodsInfo)(nil), // 16: pbentity.OrderGoodsInfo
}
var file_order_info_v1_order_info_proto_depIdxs = []int32{
	1,  // 0: order_info.v1.OrderInfoCreateReq.order_goods_info:type_name -> order_info.v1.OrderGoodsItem
	15, // 1: order_info.v1.OrderInfoGetDetailRes.order_info:type_name -> pbentity.OrderInfo
	16, // 2: order_info.v1.OrderInfoGetDetailRes.order_goods_infos:type_name -> pbentity.OrderGoodsInfo
	7,  // 3: order_info.v1.OrderListInfo.goods_info:type_name -> order_info.v1.OrderListGoodsInfo
	6,  // 4: order_info.v1.OrderInfoListResponse.list:type_name -> order_info.v1.OrderListInfo
	8,  // 5: order_info.v1.OrderInfoGetListRes.data:type_name -> order_info.v1.OrderInfoListResponse
	14, // 6: order_info.v1.NotifyReq.headers:type_name -> order_info.v1.NotifyReq.HeadersEntry
	0,  // 7: order_info.v1.order_info.Create:input_type -> order_info.v1.OrderInfoCreateReq
	3,  // 8: order_info.v1.order_info.GetDetail:input_type -> order_info.v1.OrderInfoGetDetailReq
	5,  // 9: order_info.v1.order_info.GetList:input_type -> order_info.v1.OrderInfoGetListReq
	10, // 10: order_info.v1.order_info.Payment:input_type -> order_info.v1.PaymentReq
	12, // 11: order_info.v1.order_info.Notify:input_type -> order_info.v1.NotifyReq
	2,  // 12: order_info.v1.order_info.Create:output_type -> order_info.v1.OrderInfoCreateRes
	4,  // 13: order_info.v1.order_info.GetDetail:output_type -> order_info.v1.OrderInfoGetDetailRes
	9,  // 14: order_info.v1.order_info.GetList:output_type -> order_info.v1.OrderInfoGetListRes
	11, // 15: order_info.v1.order_info.Payment:output_type -> order_info.v1.PaymentRes
	13, // 16: order_info.v1.order_info.Notify:output_type -> order_info.v1.NotifyRes
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_order_info_v1_order_info_proto_init() }
func file_order_info_v1_order_info_proto_init() {
	if File_order_info_v1_order_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_info_v1_order_info_proto_rawDesc), len(file_order_info_v1_order_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_info_v1_order_info_proto_goTypes,
		DependencyIndexes: file_order_info_v1_order_info_proto_depIdxs,
		MessageInfos:      file_order_info_v1_order_info_proto_msgTypes,
	}.Build()
	File_order_info_v1_order_info_proto = out.File
	file_order_info_v1_order_info_proto_goTypes = nil
	file_order_info_v1_order_info_proto_depIdxs = nil
}
