// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"shop-goframe-micro-service-refacotor/app/goods/internal/dao/internal"
)

// bargainInfoDao is the data access object for the table bargain_info.
// You can define custom methods on it to extend its functionality as needed.
type bargainInfoDao struct {
	*internal.BargainInfoDao
}

var (
	// BargainInfo is a globally accessible object for table bargain_info operations.
	BargainInfo = bargainInfoDao{internal.NewBargainInfoDao()}
)

// Add your custom methods and functionality below.
