// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: goods_info/v1/goods_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service-refacotor/app/goods/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortType int32

const (
	SortType_DEFAULT    SortType = 0
	SortType_PRICE_ASC  SortType = 1
	SortType_PRICE_DESC SortType = 2
	SortType_SALE_DESC  SortType = 3
)

// Enum value maps for SortType.
var (
	SortType_name = map[int32]string{
		0: "DEFAULT",
		1: "PRICE_ASC",
		2: "PRICE_DESC",
		3: "SALE_DESC",
	}
	SortType_value = map[string]int32{
		"DEFAULT":    0,
		"PRICE_ASC":  1,
		"PRICE_DESC": 2,
		"SALE_DESC":  3,
	}
)

func (x SortType) Enum() *SortType {
	p := new(SortType)
	*p = x
	return p
}

func (x SortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortType) Descriptor() protoreflect.EnumDescriptor {
	return file_goods_info_v1_goods_info_proto_enumTypes[0].Descriptor()
}

func (SortType) Type() protoreflect.EnumType {
	return &file_goods_info_v1_goods_info_proto_enumTypes[0]
}

func (x SortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortType.Descriptor instead.
func (SortType) EnumDescriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{0}
}

type GoodsInfoGetDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoGetDetailReq) Reset() {
	*x = GoodsInfoGetDetailReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoGetDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoGetDetailReq) ProtoMessage() {}

func (x *GoodsInfoGetDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoGetDetailReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoGetDetailReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsInfoGetDetailReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsInfoGetDetailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *pbentity.GoodsInfo    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoGetDetailRes) Reset() {
	*x = GoodsInfoGetDetailRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoGetDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoGetDetailRes) ProtoMessage() {}

func (x *GoodsInfoGetDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoGetDetailRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoGetDetailRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsInfoGetDetailRes) GetData() *pbentity.GoodsInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 新增消息定义
type GoodsInfoCreateReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price            uint64                 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	PicUrl           string                 `protobuf:"bytes,3,opt,name=PicUrl,proto3" json:"PicUrl,omitempty" dc:"主图"` // 主图
	Images           string                 `protobuf:"bytes,4,opt,name=Images,proto3" json:"Images,omitempty"`
	Level1CategoryId uint32                 `protobuf:"varint,5,opt,name=level1_category_id,json=level1CategoryId,proto3" json:"level1_category_id,omitempty"`
	Level2CategoryId uint32                 `protobuf:"varint,6,opt,name=level2_category_id,json=level2CategoryId,proto3" json:"level2_category_id,omitempty"`
	Level3CategoryId uint32                 `protobuf:"varint,7,opt,name=level3_category_id,json=level3CategoryId,proto3" json:"level3_category_id,omitempty"`
	Brand            string                 `protobuf:"bytes,8,opt,name=brand,proto3" json:"brand,omitempty"`
	Stock            uint32                 `protobuf:"varint,9,opt,name=stock,proto3" json:"stock,omitempty"`
	Sale             uint32                 `protobuf:"varint,10,opt,name=sale,proto3" json:"sale,omitempty"`
	Tags             string                 `protobuf:"bytes,11,opt,name=tags,proto3" json:"tags,omitempty"`
	DetailInfo       string                 `protobuf:"bytes,12,opt,name=detail_info,json=detailInfo,proto3" json:"detail_info,omitempty"`
	Sort             uint32                 `protobuf:"varint,13,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GoodsInfoCreateReq) Reset() {
	*x = GoodsInfoCreateReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoCreateReq) ProtoMessage() {}

func (x *GoodsInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoCreateReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsInfoCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetLevel1CategoryId() uint32 {
	if x != nil {
		return x.Level1CategoryId
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetLevel2CategoryId() uint32 {
	if x != nil {
		return x.Level2CategoryId
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetLevel3CategoryId() uint32 {
	if x != nil {
		return x.Level3CategoryId
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetSale() uint32 {
	if x != nil {
		return x.Sale
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetDetailInfo() string {
	if x != nil {
		return x.DetailInfo
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type GoodsInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoCreateRes) Reset() {
	*x = GoodsInfoCreateRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoCreateRes) ProtoMessage() {}

func (x *GoodsInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoCreateRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{3}
}

func (x *GoodsInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsInfoUpdateReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price            uint64                 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	PicUrl           string                 `protobuf:"bytes,4,opt,name=PicUrl,proto3" json:"PicUrl,omitempty" dc:"主图"` // 主图
	Images           string                 `protobuf:"bytes,5,opt,name=Images,proto3" json:"Images,omitempty"`
	Level1CategoryId uint32                 `protobuf:"varint,6,opt,name=level1_category_id,json=level1CategoryId,proto3" json:"level1_category_id,omitempty"`
	Level2CategoryId uint32                 `protobuf:"varint,7,opt,name=level2_category_id,json=level2CategoryId,proto3" json:"level2_category_id,omitempty"`
	Level3CategoryId uint32                 `protobuf:"varint,8,opt,name=level3_category_id,json=level3CategoryId,proto3" json:"level3_category_id,omitempty"`
	Brand            string                 `protobuf:"bytes,9,opt,name=brand,proto3" json:"brand,omitempty"`
	Stock            uint32                 `protobuf:"varint,10,opt,name=stock,proto3" json:"stock,omitempty"`
	Sale             uint32                 `protobuf:"varint,11,opt,name=sale,proto3" json:"sale,omitempty"`
	Tags             string                 `protobuf:"bytes,12,opt,name=tags,proto3" json:"tags,omitempty"`
	DetailInfo       string                 `protobuf:"bytes,13,opt,name=detail_info,json=detailInfo,proto3" json:"detail_info,omitempty"`
	Sort             uint32                 `protobuf:"varint,14,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GoodsInfoUpdateReq) Reset() {
	*x = GoodsInfoUpdateReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoUpdateReq) ProtoMessage() {}

func (x *GoodsInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{4}
}

func (x *GoodsInfoUpdateReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetLevel1CategoryId() uint32 {
	if x != nil {
		return x.Level1CategoryId
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetLevel2CategoryId() uint32 {
	if x != nil {
		return x.Level2CategoryId
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetLevel3CategoryId() uint32 {
	if x != nil {
		return x.Level3CategoryId
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetSale() uint32 {
	if x != nil {
		return x.Sale
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetDetailInfo() string {
	if x != nil {
		return x.DetailInfo
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type GoodsInfoUpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoUpdateRes) Reset() {
	*x = GoodsInfoUpdateRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoUpdateRes) ProtoMessage() {}

func (x *GoodsInfoUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoUpdateRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoUpdateRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{5}
}

func (x *GoodsInfoUpdateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoDeleteReq) Reset() {
	*x = GoodsInfoDeleteReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoDeleteReq) ProtoMessage() {}

func (x *GoodsInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{6}
}

func (x *GoodsInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoDeleteRes) Reset() {
	*x = GoodsInfoDeleteRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoDeleteRes) ProtoMessage() {}

func (x *GoodsInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{7}
}

type GoodsInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty" dc:"修改：字段编号必须从1开始递增"` // 修改：字段编号必须从1开始递增
	IsHot         uint32                 `protobuf:"varint,3,opt,name=is_hot,json=isHot,proto3" json:"is_hot,omitempty"`
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	CategoryId    uint32                 `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	PriceMin      uint64                 `protobuf:"varint,6,opt,name=price_min,json=priceMin,proto3" json:"price_min,omitempty"`
	PriceMax      uint64                 `protobuf:"varint,7,opt,name=price_max,json=priceMax,proto3" json:"price_max,omitempty"`
	SortType      SortType               `protobuf:"varint,8,opt,name=sort_type,json=sortType,proto3,enum=goods_info.v1.SortType" json:"sort_type,omitempty"`
	OnlyInStock   uint32                 `protobuf:"varint,9,opt,name=only_in_stock,json=onlyInStock,proto3" json:"only_in_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoGetListReq) Reset() {
	*x = GoodsInfoGetListReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoGetListReq) ProtoMessage() {}

func (x *GoodsInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoGetListReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{8}
}

func (x *GoodsInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GoodsInfoGetListReq) GetIsHot() uint32 {
	if x != nil {
		return x.IsHot
	}
	return 0
}

func (x *GoodsInfoGetListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GoodsInfoGetListReq) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodsInfoGetListReq) GetPriceMin() uint64 {
	if x != nil {
		return x.PriceMin
	}
	return 0
}

func (x *GoodsInfoGetListReq) GetPriceMax() uint64 {
	if x != nil {
		return x.PriceMax
	}
	return 0
}

func (x *GoodsInfoGetListReq) GetSortType() SortType {
	if x != nil {
		return x.SortType
	}
	return SortType_DEFAULT
}

func (x *GoodsInfoGetListReq) GetOnlyInStock() uint32 {
	if x != nil {
		return x.OnlyInStock
	}
	return 0
}

type GoodsInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*pbentity.GoodsInfo  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoListResponse) Reset() {
	*x = GoodsInfoListResponse{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoListResponse) ProtoMessage() {}

func (x *GoodsInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoListResponse.ProtoReflect.Descriptor instead.
func (*GoodsInfoListResponse) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{9}
}

func (x *GoodsInfoListResponse) GetList() []*pbentity.GoodsInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GoodsInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GoodsInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GoodsInfoGetListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *GoodsInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoGetListRes) Reset() {
	*x = GoodsInfoGetListRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoGetListRes) ProtoMessage() {}

func (x *GoodsInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoGetListRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{10}
}

func (x *GoodsInfoGetListRes) GetData() *GoodsInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetGoodsStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsIds      []uint32               `protobuf:"varint,1,rep,packed,name=goods_ids,json=goodsIds,proto3" json:"goods_ids,omitempty" dc:"商品列表"` // 商品列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodsStockReq) Reset() {
	*x = GetGoodsStockReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodsStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsStockReq) ProtoMessage() {}

func (x *GetGoodsStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsStockReq.ProtoReflect.Descriptor instead.
func (*GetGoodsStockReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{11}
}

func (x *GetGoodsStockReq) GetGoodsIds() []uint32 {
	if x != nil {
		return x.GoodsIds
	}
	return nil
}

type GetGoodsStockRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsStock    map[uint32]int32       `protobuf:"bytes,1,rep,name=goods_stock,json=goodsStock,proto3" json:"goods_stock,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodsStockRes) Reset() {
	*x = GetGoodsStockRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodsStockRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsStockRes) ProtoMessage() {}

func (x *GetGoodsStockRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsStockRes.ProtoReflect.Descriptor instead.
func (*GetGoodsStockRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{12}
}

func (x *GetGoodsStockRes) GetGoodsStock() map[uint32]int32 {
	if x != nil {
		return x.GoodsStock
	}
	return nil
}

type DeductStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsIds      []uint32               `protobuf:"varint,1,rep,packed,name=goods_ids,json=goodsIds,proto3" json:"goods_ids,omitempty" dc:"商品列表"` // 商品列表
	Counts        []uint32               `protobuf:"varint,2,rep,packed,name=counts,proto3" json:"counts,omitempty" dc:"商品数量"`                     // 商品数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockReq) Reset() {
	*x = DeductStockReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockReq) ProtoMessage() {}

func (x *DeductStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockReq.ProtoReflect.Descriptor instead.
func (*DeductStockReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{13}
}

func (x *DeductStockReq) GetGoodsIds() []uint32 {
	if x != nil {
		return x.GoodsIds
	}
	return nil
}

func (x *DeductStockReq) GetCounts() []uint32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

type DeductStockRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockRes) Reset() {
	*x = DeductStockRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockRes) ProtoMessage() {}

func (x *DeductStockRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockRes.ProtoReflect.Descriptor instead.
func (*DeductStockRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{14}
}

type RestoreStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsIds      []uint32               `protobuf:"varint,1,rep,packed,name=goods_ids,json=goodsIds,proto3" json:"goods_ids,omitempty" dc:"商品列表"` // 商品列表
	Counts        []uint32               `protobuf:"varint,2,rep,packed,name=counts,proto3" json:"counts,omitempty" dc:"商品数量"`                     // 商品数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreStockReq) Reset() {
	*x = RestoreStockReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStockReq) ProtoMessage() {}

func (x *RestoreStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStockReq.ProtoReflect.Descriptor instead.
func (*RestoreStockReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{15}
}

func (x *RestoreStockReq) GetGoodsIds() []uint32 {
	if x != nil {
		return x.GoodsIds
	}
	return nil
}

func (x *RestoreStockReq) GetCounts() []uint32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

type RestoreStockRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreStockRes) Reset() {
	*x = RestoreStockRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreStockRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStockRes) ProtoMessage() {}

func (x *RestoreStockRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStockRes.ProtoReflect.Descriptor instead.
func (*RestoreStockRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{16}
}

type IncreaseSalesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsIds      []uint32               `protobuf:"varint,1,rep,packed,name=goods_ids,json=goodsIds,proto3" json:"goods_ids,omitempty" dc:"商品列表"` // 商品列表
	Counts        []uint32               `protobuf:"varint,2,rep,packed,name=counts,proto3" json:"counts,omitempty" dc:"商品数量"`                     // 商品数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseSalesReq) Reset() {
	*x = IncreaseSalesReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseSalesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseSalesReq) ProtoMessage() {}

func (x *IncreaseSalesReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseSalesReq.ProtoReflect.Descriptor instead.
func (*IncreaseSalesReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{17}
}

func (x *IncreaseSalesReq) GetGoodsIds() []uint32 {
	if x != nil {
		return x.GoodsIds
	}
	return nil
}

func (x *IncreaseSalesReq) GetCounts() []uint32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

type IncreaseSalesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseSalesRes) Reset() {
	*x = IncreaseSalesRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseSalesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseSalesRes) ProtoMessage() {}

func (x *IncreaseSalesRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseSalesRes.ProtoReflect.Descriptor instead.
func (*IncreaseSalesRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{18}
}

var File_goods_info_v1_goods_info_proto protoreflect.FileDescriptor

const file_goods_info_v1_goods_info_proto_rawDesc = "" +
	"\n" +
	"\x1egoods_info/v1/goods_info.proto\x12\rgoods_info.v1\x1a\x19pbentity/goods_info.proto\"'\n" +
	"\x15GoodsInfoGetDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"@\n" +
	"\x15GoodsInfoGetDetailRes\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.pbentity.GoodsInfoR\x04data\"\x81\x03\n" +
	"\x12GoodsInfoCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x04R\x05price\x12\x16\n" +
	"\x06PicUrl\x18\x03 \x01(\tR\x06PicUrl\x12\x16\n" +
	"\x06Images\x18\x04 \x01(\tR\x06Images\x12,\n" +
	"\x12level1_category_id\x18\x05 \x01(\rR\x10level1CategoryId\x12,\n" +
	"\x12level2_category_id\x18\x06 \x01(\rR\x10level2CategoryId\x12,\n" +
	"\x12level3_category_id\x18\a \x01(\rR\x10level3CategoryId\x12\x14\n" +
	"\x05brand\x18\b \x01(\tR\x05brand\x12\x14\n" +
	"\x05stock\x18\t \x01(\rR\x05stock\x12\x12\n" +
	"\x04sale\x18\n" +
	" \x01(\rR\x04sale\x12\x12\n" +
	"\x04tags\x18\v \x01(\tR\x04tags\x12\x1f\n" +
	"\vdetail_info\x18\f \x01(\tR\n" +
	"detailInfo\x12\x12\n" +
	"\x04sort\x18\r \x01(\rR\x04sort\"$\n" +
	"\x12GoodsInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x91\x03\n" +
	"\x12GoodsInfoUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x04R\x05price\x12\x16\n" +
	"\x06PicUrl\x18\x04 \x01(\tR\x06PicUrl\x12\x16\n" +
	"\x06Images\x18\x05 \x01(\tR\x06Images\x12,\n" +
	"\x12level1_category_id\x18\x06 \x01(\rR\x10level1CategoryId\x12,\n" +
	"\x12level2_category_id\x18\a \x01(\rR\x10level2CategoryId\x12,\n" +
	"\x12level3_category_id\x18\b \x01(\rR\x10level3CategoryId\x12\x14\n" +
	"\x05brand\x18\t \x01(\tR\x05brand\x12\x14\n" +
	"\x05stock\x18\n" +
	" \x01(\rR\x05stock\x12\x12\n" +
	"\x04sale\x18\v \x01(\rR\x04sale\x12\x12\n" +
	"\x04tags\x18\f \x01(\tR\x04tags\x12\x1f\n" +
	"\vdetail_info\x18\r \x01(\tR\n" +
	"detailInfo\x12\x12\n" +
	"\x04sort\x18\x0e \x01(\rR\x04sort\"$\n" +
	"\x12GoodsInfoUpdateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"$\n" +
	"\x12GoodsInfoDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x14\n" +
	"\x12GoodsInfoDeleteRes\"\xa3\x02\n" +
	"\x13GoodsInfoGetListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x15\n" +
	"\x06is_hot\x18\x03 \x01(\rR\x05isHot\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\rR\n" +
	"categoryId\x12\x1b\n" +
	"\tprice_min\x18\x06 \x01(\x04R\bpriceMin\x12\x1b\n" +
	"\tprice_max\x18\a \x01(\x04R\bpriceMax\x124\n" +
	"\tsort_type\x18\b \x01(\x0e2\x17.goods_info.v1.SortTypeR\bsortType\x12\"\n" +
	"\ronly_in_stock\x18\t \x01(\rR\vonlyInStock\"~\n" +
	"\x15GoodsInfoListResponse\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.pbentity.GoodsInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"O\n" +
	"\x13GoodsInfoGetListRes\x128\n" +
	"\x04data\x18\x01 \x01(\v2$.goods_info.v1.GoodsInfoListResponseR\x04data\"/\n" +
	"\x10GetGoodsStockReq\x12\x1b\n" +
	"\tgoods_ids\x18\x01 \x03(\rR\bgoodsIds\"\xa3\x01\n" +
	"\x10GetGoodsStockRes\x12P\n" +
	"\vgoods_stock\x18\x01 \x03(\v2/.goods_info.v1.GetGoodsStockRes.GoodsStockEntryR\n" +
	"goodsStock\x1a=\n" +
	"\x0fGoodsStockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"E\n" +
	"\x0eDeductStockReq\x12\x1b\n" +
	"\tgoods_ids\x18\x01 \x03(\rR\bgoodsIds\x12\x16\n" +
	"\x06counts\x18\x02 \x03(\rR\x06counts\"\x10\n" +
	"\x0eDeductStockRes\"F\n" +
	"\x0fRestoreStockReq\x12\x1b\n" +
	"\tgoods_ids\x18\x01 \x03(\rR\bgoodsIds\x12\x16\n" +
	"\x06counts\x18\x02 \x03(\rR\x06counts\"\x11\n" +
	"\x0fRestoreStockRes\"G\n" +
	"\x10IncreaseSalesReq\x12\x1b\n" +
	"\tgoods_ids\x18\x01 \x03(\rR\bgoodsIds\x12\x16\n" +
	"\x06counts\x18\x02 \x03(\rR\x06counts\"\x12\n" +
	"\x10IncreaseSalesRes*E\n" +
	"\bSortType\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\r\n" +
	"\tPRICE_ASC\x10\x01\x12\x0e\n" +
	"\n" +
	"PRICE_DESC\x10\x02\x12\r\n" +
	"\tSALE_DESC\x10\x032\xfd\x05\n" +
	"\n" +
	"goods_info\x12S\n" +
	"\aGetList\x12\".goods_info.v1.GoodsInfoGetListReq\x1a\".goods_info.v1.GoodsInfoGetListRes\"\x00\x12Y\n" +
	"\tGetDetail\x12$.goods_info.v1.GoodsInfoGetDetailReq\x1a$.goods_info.v1.GoodsInfoGetDetailRes\"\x00\x12P\n" +
	"\x06Create\x12!.goods_info.v1.GoodsInfoCreateReq\x1a!.goods_info.v1.GoodsInfoCreateRes\"\x00\x12P\n" +
	"\x06Update\x12!.goods_info.v1.GoodsInfoUpdateReq\x1a!.goods_info.v1.GoodsInfoUpdateRes\"\x00\x12P\n" +
	"\x06Delete\x12!.goods_info.v1.GoodsInfoDeleteReq\x1a!.goods_info.v1.GoodsInfoDeleteRes\"\x00\x12S\n" +
	"\rGetGoodsStock\x12\x1f.goods_info.v1.GetGoodsStockReq\x1a\x1f.goods_info.v1.GetGoodsStockRes\"\x00\x12M\n" +
	"\vDeductStock\x12\x1d.goods_info.v1.DeductStockReq\x1a\x1d.goods_info.v1.DeductStockRes\"\x00\x12P\n" +
	"\fRestoreStock\x12\x1e.goods_info.v1.RestoreStockReq\x1a\x1e.goods_info.v1.RestoreStockRes\"\x00\x12S\n" +
	"\rIncreaseSales\x12\x1f.goods_info.v1.IncreaseSalesReq\x1a\x1f.goods_info.v1.IncreaseSalesRes\"\x00B8Z6shop-goframe-micro-service/app/goods/api/goods_info/v1b\x06proto3"

var (
	file_goods_info_v1_goods_info_proto_rawDescOnce sync.Once
	file_goods_info_v1_goods_info_proto_rawDescData []byte
)

func file_goods_info_v1_goods_info_proto_rawDescGZIP() []byte {
	file_goods_info_v1_goods_info_proto_rawDescOnce.Do(func() {
		file_goods_info_v1_goods_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goods_info_v1_goods_info_proto_rawDesc), len(file_goods_info_v1_goods_info_proto_rawDesc)))
	})
	return file_goods_info_v1_goods_info_proto_rawDescData
}

var file_goods_info_v1_goods_info_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_goods_info_v1_goods_info_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_goods_info_v1_goods_info_proto_goTypes = []any{
	(SortType)(0),                 // 0: goods_info.v1.SortType
	(*GoodsInfoGetDetailReq)(nil), // 1: goods_info.v1.GoodsInfoGetDetailReq
	(*GoodsInfoGetDetailRes)(nil), // 2: goods_info.v1.GoodsInfoGetDetailRes
	(*GoodsInfoCreateReq)(nil),    // 3: goods_info.v1.GoodsInfoCreateReq
	(*GoodsInfoCreateRes)(nil),    // 4: goods_info.v1.GoodsInfoCreateRes
	(*GoodsInfoUpdateReq)(nil),    // 5: goods_info.v1.GoodsInfoUpdateReq
	(*GoodsInfoUpdateRes)(nil),    // 6: goods_info.v1.GoodsInfoUpdateRes
	(*GoodsInfoDeleteReq)(nil),    // 7: goods_info.v1.GoodsInfoDeleteReq
	(*GoodsInfoDeleteRes)(nil),    // 8: goods_info.v1.GoodsInfoDeleteRes
	(*GoodsInfoGetListReq)(nil),   // 9: goods_info.v1.GoodsInfoGetListReq
	(*GoodsInfoListResponse)(nil), // 10: goods_info.v1.GoodsInfoListResponse
	(*GoodsInfoGetListRes)(nil),   // 11: goods_info.v1.GoodsInfoGetListRes
	(*GetGoodsStockReq)(nil),      // 12: goods_info.v1.GetGoodsStockReq
	(*GetGoodsStockRes)(nil),      // 13: goods_info.v1.GetGoodsStockRes
	(*DeductStockReq)(nil),        // 14: goods_info.v1.DeductStockReq
	(*DeductStockRes)(nil),        // 15: goods_info.v1.DeductStockRes
	(*RestoreStockReq)(nil),       // 16: goods_info.v1.RestoreStockReq
	(*RestoreStockRes)(nil),       // 17: goods_info.v1.RestoreStockRes
	(*IncreaseSalesReq)(nil),      // 18: goods_info.v1.IncreaseSalesReq
	(*IncreaseSalesRes)(nil),      // 19: goods_info.v1.IncreaseSalesRes
	nil,                           // 20: goods_info.v1.GetGoodsStockRes.GoodsStockEntry
	(*pbentity.GoodsInfo)(nil),    // 21: pbentity.GoodsInfo
}
var file_goods_info_v1_goods_info_proto_depIdxs = []int32{
	21, // 0: goods_info.v1.GoodsInfoGetDetailRes.data:type_name -> pbentity.GoodsInfo
	0,  // 1: goods_info.v1.GoodsInfoGetListReq.sort_type:type_name -> goods_info.v1.SortType
	21, // 2: goods_info.v1.GoodsInfoListResponse.list:type_name -> pbentity.GoodsInfo
	10, // 3: goods_info.v1.GoodsInfoGetListRes.data:type_name -> goods_info.v1.GoodsInfoListResponse
	20, // 4: goods_info.v1.GetGoodsStockRes.goods_stock:type_name -> goods_info.v1.GetGoodsStockRes.GoodsStockEntry
	9,  // 5: goods_info.v1.goods_info.GetList:input_type -> goods_info.v1.GoodsInfoGetListReq
	1,  // 6: goods_info.v1.goods_info.GetDetail:input_type -> goods_info.v1.GoodsInfoGetDetailReq
	3,  // 7: goods_info.v1.goods_info.Create:input_type -> goods_info.v1.GoodsInfoCreateReq
	5,  // 8: goods_info.v1.goods_info.Update:input_type -> goods_info.v1.GoodsInfoUpdateReq
	7,  // 9: goods_info.v1.goods_info.Delete:input_type -> goods_info.v1.GoodsInfoDeleteReq
	12, // 10: goods_info.v1.goods_info.GetGoodsStock:input_type -> goods_info.v1.GetGoodsStockReq
	14, // 11: goods_info.v1.goods_info.DeductStock:input_type -> goods_info.v1.DeductStockReq
	16, // 12: goods_info.v1.goods_info.RestoreStock:input_type -> goods_info.v1.RestoreStockReq
	18, // 13: goods_info.v1.goods_info.IncreaseSales:input_type -> goods_info.v1.IncreaseSalesReq
	11, // 14: goods_info.v1.goods_info.GetList:output_type -> goods_info.v1.GoodsInfoGetListRes
	2,  // 15: goods_info.v1.goods_info.GetDetail:output_type -> goods_info.v1.GoodsInfoGetDetailRes
	4,  // 16: goods_info.v1.goods_info.Create:output_type -> goods_info.v1.GoodsInfoCreateRes
	6,  // 17: goods_info.v1.goods_info.Update:output_type -> goods_info.v1.GoodsInfoUpdateRes
	8,  // 18: goods_info.v1.goods_info.Delete:output_type -> goods_info.v1.GoodsInfoDeleteRes
	13, // 19: goods_info.v1.goods_info.GetGoodsStock:output_type -> goods_info.v1.GetGoodsStockRes
	15, // 20: goods_info.v1.goods_info.DeductStock:output_type -> goods_info.v1.DeductStockRes
	17, // 21: goods_info.v1.goods_info.RestoreStock:output_type -> goods_info.v1.RestoreStockRes
	19, // 22: goods_info.v1.goods_info.IncreaseSales:output_type -> goods_info.v1.IncreaseSalesRes
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_goods_info_v1_goods_info_proto_init() }
func file_goods_info_v1_goods_info_proto_init() {
	if File_goods_info_v1_goods_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goods_info_v1_goods_info_proto_rawDesc), len(file_goods_info_v1_goods_info_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_info_v1_goods_info_proto_goTypes,
		DependencyIndexes: file_goods_info_v1_goods_info_proto_depIdxs,
		EnumInfos:         file_goods_info_v1_goods_info_proto_enumTypes,
		MessageInfos:      file_goods_info_v1_goods_info_proto_msgTypes,
	}.Build()
	File_goods_info_v1_goods_info_proto = out.File
	file_goods_info_v1_goods_info_proto_goTypes = nil
	file_goods_info_v1_goods_info_proto_depIdxs = nil
}
