server:
  address: ":8499"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  logger:
    path: "./log"
    file: "{Y-m-d}.log"
    prefix: "search-service"
    level: "all"
    stdout: true
    rotateSize: 104857600
    rotateBackupLimit: 7
    ctxKeys: [ "traceId" ]
    timeFormat: "2006-01-02 15:04:05.000"

etcd:
  address: "etcd:2379"

elasticsearch:
  address: "http://elasticsearch:9200"
  sniff: false
  healthcheck: true
  indices:
    goods: "mall_goods"

binlog:
  goods:
    mysql:
      host: "mysql"
      port: 3306
      username: "root"
root:zK8!pW#s&t@5g$E7hN*d@tcp
