// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: collection_info/v1/collection_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service-refacotor/app/interaction/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增消息定义
type CollectionInfoCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户id"`     // 用户id
	ObjectId      uint32                 `protobuf:"varint,2,opt,name=ObjectId,proto3" json:"ObjectId,omitempty" dc:"对象id"` // 对象id
	Type          uint32                 `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty" dc:"收藏类型：1商品 2文章"` // 收藏类型：1商品 2文章
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionInfoCreateReq) Reset() {
	*x = CollectionInfoCreateReq{}
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoCreateReq) ProtoMessage() {}

func (x *CollectionInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoCreateReq.ProtoReflect.Descriptor instead.
func (*CollectionInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionInfoCreateReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CollectionInfoCreateReq) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *CollectionInfoCreateReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type CollectionInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionInfoCreateRes) Reset() {
	*x = CollectionInfoCreateRes{}
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoCreateRes) ProtoMessage() {}

func (x *CollectionInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoCreateRes.ProtoReflect.Descriptor instead.
func (*CollectionInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{1}
}

func (x *CollectionInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CollectionInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"收藏id"`         // 收藏id
	UserId        uint32                 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户id"` // 用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionInfoDeleteReq) Reset() {
	*x = CollectionInfoDeleteReq{}
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoDeleteReq) ProtoMessage() {}

func (x *CollectionInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*CollectionInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{2}
}

func (x *CollectionInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CollectionInfoDeleteReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CollectionInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionInfoDeleteRes) Reset() {
	*x = CollectionInfoDeleteRes{}
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoDeleteRes) ProtoMessage() {}

func (x *CollectionInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*CollectionInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{3}
}

func (x *CollectionInfoDeleteRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CollectionInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户id"`               // 用户id
	Type          uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty" dc:"收藏类型：1商品 2文章"`           // 收藏类型：1商品 2文章
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty" dc:"第几页。"`                   // 第几页。
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty" dc:"每页显示几个。修改：字段编号必须从1开始递增"` // 每页显示几个。修改：字段编号必须从1开始递增
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionInfoGetListReq) Reset() {
	*x = CollectionInfoGetListReq{}
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoGetListReq) ProtoMessage() {}

func (x *CollectionInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoGetListReq.ProtoReflect.Descriptor instead.
func (*CollectionInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{4}
}

func (x *CollectionInfoGetListReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CollectionInfoGetListReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CollectionInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CollectionInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CollectionInfoListResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	List          []*pbentity.CollectionInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                     `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                     `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                     `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionInfoListResponse) Reset() {
	*x = CollectionInfoListResponse{}
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoListResponse) ProtoMessage() {}

func (x *CollectionInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoListResponse.ProtoReflect.Descriptor instead.
func (*CollectionInfoListResponse) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{5}
}

func (x *CollectionInfoListResponse) GetList() []*pbentity.CollectionInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CollectionInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CollectionInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CollectionInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CollectionInfoGetListRes struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Data          *CollectionInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionInfoGetListRes) Reset() {
	*x = CollectionInfoGetListRes{}
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoGetListRes) ProtoMessage() {}

func (x *CollectionInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoGetListRes.ProtoReflect.Descriptor instead.
func (*CollectionInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{6}
}

func (x *CollectionInfoGetListRes) GetData() *CollectionInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_collection_info_v1_collection_info_proto protoreflect.FileDescriptor

const file_collection_info_v1_collection_info_proto_rawDesc = "" +
	"\n" +
	"(collection_info/v1/collection_info.proto\x12\x12collection_info.v1\x1a\x1epbentity/collection_info.proto\"a\n" +
	"\x17CollectionInfoCreateReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\rR\x06UserId\x12\x1a\n" +
	"\bObjectId\x18\x02 \x01(\rR\bObjectId\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\rR\x04Type\")\n" +
	"\x17CollectionInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"A\n" +
	"\x17CollectionInfoDeleteReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\rR\x06UserId\")\n" +
	"\x17CollectionInfoDeleteRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"n\n" +
	"\x18CollectionInfoGetListReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\rR\x06UserId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\"\x88\x01\n" +
	"\x1aCollectionInfoListResponse\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.pbentity.CollectionInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"^\n" +
	"\x18CollectionInfoGetListRes\x12B\n" +
	"\x04data\x18\x01 \x01(\v2..collection_info.v1.CollectionInfoListResponseR\x04data2\xc6\x02\n" +
	"\x0fcollection_info\x12g\n" +
	"\aGetList\x12,.collection_info.v1.CollectionInfoGetListReq\x1a,.collection_info.v1.CollectionInfoGetListRes\"\x00\x12d\n" +
	"\x06Create\x12+.collection_info.v1.CollectionInfoCreateReq\x1a+.collection_info.v1.CollectionInfoCreateRes\"\x00\x12d\n" +
	"\x06Delete\x12+.collection_info.v1.CollectionInfoDeleteReq\x1a+.collection_info.v1.CollectionInfoDeleteRes\"\x00BLZJshop-goframe-micro-service-refacotor/app/collection/api/collection_info/v1b\x06proto3"

var (
	file_collection_info_v1_collection_info_proto_rawDescOnce sync.Once
	file_collection_info_v1_collection_info_proto_rawDescData []byte
)

func file_collection_info_v1_collection_info_proto_rawDescGZIP() []byte {
	file_collection_info_v1_collection_info_proto_rawDescOnce.Do(func() {
		file_collection_info_v1_collection_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collection_info_v1_collection_info_proto_rawDesc), len(file_collection_info_v1_collection_info_proto_rawDesc)))
	})
	return file_collection_info_v1_collection_info_proto_rawDescData
}

var file_collection_info_v1_collection_info_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_collection_info_v1_collection_info_proto_goTypes = []any{
	(*CollectionInfoCreateReq)(nil),    // 0: collection_info.v1.CollectionInfoCreateReq
	(*CollectionInfoCreateRes)(nil),    // 1: collection_info.v1.CollectionInfoCreateRes
	(*CollectionInfoDeleteReq)(nil),    // 2: collection_info.v1.CollectionInfoDeleteReq
	(*CollectionInfoDeleteRes)(nil),    // 3: collection_info.v1.CollectionInfoDeleteRes
	(*CollectionInfoGetListReq)(nil),   // 4: collection_info.v1.CollectionInfoGetListReq
	(*CollectionInfoListResponse)(nil), // 5: collection_info.v1.CollectionInfoListResponse
	(*CollectionInfoGetListRes)(nil),   // 6: collection_info.v1.CollectionInfoGetListRes
	(*pbentity.CollectionInfo)(nil),    // 7: pbentity.CollectionInfo
}
var file_collection_info_v1_collection_info_proto_depIdxs = []int32{
	7, // 0: collection_info.v1.CollectionInfoListResponse.list:type_name -> pbentity.CollectionInfo
	5, // 1: collection_info.v1.CollectionInfoGetListRes.data:type_name -> collection_info.v1.CollectionInfoListResponse
	4, // 2: collection_info.v1.collection_info.GetList:input_type -> collection_info.v1.CollectionInfoGetListReq
	0, // 3: collection_info.v1.collection_info.Create:input_type -> collection_info.v1.CollectionInfoCreateReq
	2, // 4: collection_info.v1.collection_info.Delete:input_type -> collection_info.v1.CollectionInfoDeleteReq
	6, // 5: collection_info.v1.collection_info.GetList:output_type -> collection_info.v1.CollectionInfoGetListRes
	1, // 6: collection_info.v1.collection_info.Create:output_type -> collection_info.v1.CollectionInfoCreateRes
	3, // 7: collection_info.v1.collection_info.Delete:output_type -> collection_info.v1.CollectionInfoDeleteRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_collection_info_v1_collection_info_proto_init() }
func file_collection_info_v1_collection_info_proto_init() {
	if File_collection_info_v1_collection_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collection_info_v1_collection_info_proto_rawDesc), len(file_collection_info_v1_collection_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collection_info_v1_collection_info_proto_goTypes,
		DependencyIndexes: file_collection_info_v1_collection_info_proto_depIdxs,
		MessageInfos:      file_collection_info_v1_collection_info_proto_msgTypes,
	}.Build()
	File_collection_info_v1_collection_info_proto = out.File
	file_collection_info_v1_collection_info_proto_goTypes = nil
	file_collection_info_v1_collection_info_proto_depIdxs = nil
}
