// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: bargain_info/v1/bargain_info.proto

package template

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BargainInfo_GetList_FullMethodName = "/bargain_info.v1.bargain_info/GetList"
	BargainInfo_Create_FullMethodName  = "/bargain_info.v1.bargain_info/Create"
	BargainInfo_Delete_FullMethodName  = "/bargain_info.v1.bargain_info/Delete"
)

// BargainInfoClient is the client API for BargainInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BargainInfoClient interface {
	GetList(ctx context.Context, in *BargainInfoGetListReq, opts ...grpc.CallOption) (*BargainInfoGetListRes, error)
	Create(ctx context.Context, in *BargainInfoCreateReq, opts ...grpc.CallOption) (*BargainInfoCreateRes, error)
	Delete(ctx context.Context, in *BargainInfoDeleteReq, opts ...grpc.CallOption) (*BargainInfoDeleteRes, error)
}

type bargainInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewBargainInfoClient(cc grpc.ClientConnInterface) BargainInfoClient {
	return &bargainInfoClient{cc}
}

func (c *bargainInfoClient) GetList(ctx context.Context, in *BargainInfoGetListReq, opts ...grpc.CallOption) (*BargainInfoGetListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BargainInfoGetListRes)
	err := c.cc.Invoke(ctx, BargainInfo_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bargainInfoClient) Create(ctx context.Context, in *BargainInfoCreateReq, opts ...grpc.CallOption) (*BargainInfoCreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BargainInfoCreateRes)
	err := c.cc.Invoke(ctx, BargainInfo_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bargainInfoClient) Delete(ctx context.Context, in *BargainInfoDeleteReq, opts ...grpc.CallOption) (*BargainInfoDeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BargainInfoDeleteRes)
	err := c.cc.Invoke(ctx, BargainInfo_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BargainInfoServer is the server API for BargainInfo service.
// All implementations must embed UnimplementedBargainInfoServer
// for forward compatibility.
type BargainInfoServer interface {
	GetList(context.Context, *BargainInfoGetListReq) (*BargainInfoGetListRes, error)
	Create(context.Context, *BargainInfoCreateReq) (*BargainInfoCreateRes, error)
	Delete(context.Context, *BargainInfoDeleteReq) (*BargainInfoDeleteRes, error)
	mustEmbedUnimplementedBargainInfoServer()
}

// UnimplementedBargainInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBargainInfoServer struct{}

func (UnimplementedBargainInfoServer) GetList(context.Context, *BargainInfoGetListReq) (*BargainInfoGetListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedBargainInfoServer) Create(context.Context, *BargainInfoCreateReq) (*BargainInfoCreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBargainInfoServer) Delete(context.Context, *BargainInfoDeleteReq) (*BargainInfoDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBargainInfoServer) mustEmbedUnimplementedBargainInfoServer() {}
func (UnimplementedBargainInfoServer) testEmbeddedByValue()                     {}

// UnsafeBargainInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BargainInfoServer will
// result in compilation errors.
type UnsafeBargainInfoServer interface {
	mustEmbedUnimplementedBargainInfoServer()
}

func RegisterBargainInfoServer(s grpc.ServiceRegistrar, srv BargainInfoServer) {
	// If the following call pancis, it indicates UnimplementedBargainInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BargainInfo_ServiceDesc, srv)
}

func _BargainInfo_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BargainInfoGetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BargainInfoServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BargainInfo_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BargainInfoServer).GetList(ctx, req.(*BargainInfoGetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BargainInfo_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BargainInfoCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BargainInfoServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BargainInfo_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BargainInfoServer).Create(ctx, req.(*BargainInfoCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BargainInfo_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BargainInfoDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BargainInfoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BargainInfo_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BargainInfoServer).Delete(ctx, req.(*BargainInfoDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BargainInfo_ServiceDesc is the grpc.ServiceDesc for BargainInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BargainInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bargain_info.v1.bargain_info",
	HandlerType: (*BargainInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _BargainInfo_GetList_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _BargainInfo_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BargainInfo_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bargain_info/v1/bargain_info.proto",
}
