// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: bargain_info/v1/bargain_info.proto

package template

import (
	reflect "reflect"
	_ "shop-goframe-micro-service-refacotor/app/goods/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 砍价信息-创建-请求体
type BargainInfoCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty" dc:"创建砍价信息的用户id"` //创建砍价信息的用户id
	GoodsID       int32                  `protobuf:"varint,2,opt,name=GoodsID,proto3" json:"GoodsID,omitempty" dc:"要砍价的商品id"`  //要砍价的商品id
	Counts        int32                  `protobuf:"varint,3,opt,name=counts,proto3" json:"counts,omitempty" dc:"最大帮砍次数"`      //最大帮砍次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainInfoCreateReq) Reset() {
	*x = BargainInfoCreateReq{}
	mi := &file_bargain_info_v1_bargain_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainInfoCreateReq) ProtoMessage() {}

func (x *BargainInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_bargain_info_v1_bargain_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainInfoCreateReq.ProtoReflect.Descriptor instead.
func (*BargainInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_bargain_info_v1_bargain_info_proto_rawDescGZIP(), []int{0}
}

func (x *BargainInfoCreateReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BargainInfoCreateReq) GetGoodsID() int32 {
	if x != nil {
		return x.GoodsID
	}
	return 0
}

func (x *BargainInfoCreateReq) GetCounts() int32 {
	if x != nil {
		return x.Counts
	}
	return 0
}

// 砍价信息-创建-响应体
type BargainInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"砍价信息id"`                //砍价信息id
	UserId        int32                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"创建砍价的用户id"`     //创建砍价的用户id
	GoodsId       int32                  `protobuf:"varint,3,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"砍价商品id"`      //砍价商品id
	Counts        int32                  `protobuf:"varint,4,opt,name=Counts,proto3" json:"Counts,omitempty" dc:"最大帮砍次数"`        //最大帮砍次数
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty" dc:"创建时间"` //创建时间
	ExpiredTime   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ExpiredTime,proto3" json:"ExpiredTime,omitempty" dc:"失效时间"` //失效时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainInfoCreateRes) Reset() {
	*x = BargainInfoCreateRes{}
	mi := &file_bargain_info_v1_bargain_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainInfoCreateRes) ProtoMessage() {}

func (x *BargainInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_bargain_info_v1_bargain_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainInfoCreateRes.ProtoReflect.Descriptor instead.
func (*BargainInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_bargain_info_v1_bargain_info_proto_rawDescGZIP(), []int{1}
}

func (x *BargainInfoCreateRes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BargainInfoCreateRes) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BargainInfoCreateRes) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *BargainInfoCreateRes) GetCounts() int32 {
	if x != nil {
		return x.Counts
	}
	return 0
}

func (x *BargainInfoCreateRes) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *BargainInfoCreateRes) GetExpiredTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredTime
	}
	return nil
}

// 砍价信息-查询-请求体
type BargainInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"砍价信息id"`         //砍价信息id
	UserId        int32                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户id"`   //用户id
	GoodsId       int32                  `protobuf:"varint,3,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"商品id"` // 商品id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainInfoGetListReq) Reset() {
	*x = BargainInfoGetListReq{}
	mi := &file_bargain_info_v1_bargain_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainInfoGetListReq) ProtoMessage() {}

func (x *BargainInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_bargain_info_v1_bargain_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainInfoGetListReq.ProtoReflect.Descriptor instead.
func (*BargainInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_bargain_info_v1_bargain_info_proto_rawDescGZIP(), []int{2}
}

func (x *BargainInfoGetListReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BargainInfoGetListReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BargainInfoGetListReq) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

// 砍价信息-查询-响应体
type BargainInfoGetListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"砍价信息id"`                    //砍价信息id
	UserId        int32                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"创建砍价的用户id"`         //创建砍价的用户id
	GoodsId       int32                  `protobuf:"varint,3,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"砍价商品id"`          //砍价商品id
	Counts        int32                  `protobuf:"varint,4,opt,name=Counts,proto3" json:"Counts,omitempty" dc:"最大帮砍次数"`            //最大帮砍次数
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty" dc:"创建时间"`     //创建时间
	UpdatedTime   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdatedTime,proto3" json:"UpdatedTime,omitempty" dc:"最新一次帮砍时间"` //最新一次帮砍时间
	ExpiredTime   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ExpiredTime,proto3" json:"ExpiredTime,omitempty" dc:"失效时间"`     //失效时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainInfoGetListRes) Reset() {
	*x = BargainInfoGetListRes{}
	mi := &file_bargain_info_v1_bargain_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainInfoGetListRes) ProtoMessage() {}

func (x *BargainInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_bargain_info_v1_bargain_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainInfoGetListRes.ProtoReflect.Descriptor instead.
func (*BargainInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_bargain_info_v1_bargain_info_proto_rawDescGZIP(), []int{3}
}

func (x *BargainInfoGetListRes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BargainInfoGetListRes) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BargainInfoGetListRes) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *BargainInfoGetListRes) GetCounts() int32 {
	if x != nil {
		return x.Counts
	}
	return 0
}

func (x *BargainInfoGetListRes) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *BargainInfoGetListRes) GetUpdatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedTime
	}
	return nil
}

func (x *BargainInfoGetListRes) GetExpiredTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredTime
	}
	return nil
}

// 砍价信息-删除-请求体
type BargainInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"创建砍价信息的id"` //创建砍价信息的id
	GoodsId       int32                  `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"砍价商品id"`  //砍价商品id
	Id            int32                  `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty" dc:"实际的id"`             //实际的id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainInfoDeleteReq) Reset() {
	*x = BargainInfoDeleteReq{}
	mi := &file_bargain_info_v1_bargain_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainInfoDeleteReq) ProtoMessage() {}

func (x *BargainInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_bargain_info_v1_bargain_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*BargainInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_bargain_info_v1_bargain_info_proto_rawDescGZIP(), []int{4}
}

func (x *BargainInfoDeleteReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BargainInfoDeleteReq) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *BargainInfoDeleteReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 砍价信息-删除-响应体
type BargainInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"砍价信息id"`                  //砍价信息id
	UserId        int32                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"发起砍价用户"`          //发起砍价用户
	GoodsId       int32                  `protobuf:"varint,3,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"对应商品id"`        //对应商品id
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty" dc:"创建时间"`   //创建时间
	UpdatedTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=UpdatedTime,proto3" json:"UpdatedTime,omitempty" dc:"最新更改时间"` //最新更改时间
	DeletedTime   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=DeletedTime,proto3" json:"DeletedTime,omitempty" dc:"删除时间"`   //删除时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainInfoDeleteRes) Reset() {
	*x = BargainInfoDeleteRes{}
	mi := &file_bargain_info_v1_bargain_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainInfoDeleteRes) ProtoMessage() {}

func (x *BargainInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_bargain_info_v1_bargain_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*BargainInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_bargain_info_v1_bargain_info_proto_rawDescGZIP(), []int{5}
}

func (x *BargainInfoDeleteRes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BargainInfoDeleteRes) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BargainInfoDeleteRes) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *BargainInfoDeleteRes) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *BargainInfoDeleteRes) GetUpdatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedTime
	}
	return nil
}

func (x *BargainInfoDeleteRes) GetDeletedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedTime
	}
	return nil
}

var File_bargain_info_v1_bargain_info_proto protoreflect.FileDescriptor

const file_bargain_info_v1_bargain_info_proto_rawDesc = "" +
	"\n" +
	"\"bargain_info/v1/bargain_info.proto\x12\x0fbargain_info.v1\x1a\x1bpbentity/bargain_info.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"`\n" +
	"\x14BargainInfoCreateReq\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x05R\x06UserID\x12\x18\n" +
	"\aGoodsID\x18\x02 \x01(\x05R\aGoodsID\x12\x16\n" +
	"\x06counts\x18\x03 \x01(\x05R\x06counts\"\xec\x01\n" +
	"\x14BargainInfoCreateRes\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x05R\x06UserId\x12\x18\n" +
	"\aGoodsId\x18\x03 \x01(\x05R\aGoodsId\x12\x16\n" +
	"\x06Counts\x18\x04 \x01(\x05R\x06Counts\x12<\n" +
	"\vCreatedTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vCreatedTime\x12<\n" +
	"\vExpiredTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vExpiredTime\"Y\n" +
	"\x15BargainInfoGetListReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x05R\x06UserId\x12\x18\n" +
	"\aGoodsId\x18\x03 \x01(\x05R\aGoodsId\"\xab\x02\n" +
	"\x15BargainInfoGetListRes\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x05R\x06UserId\x12\x18\n" +
	"\aGoodsId\x18\x03 \x01(\x05R\aGoodsId\x12\x16\n" +
	"\x06Counts\x18\x04 \x01(\x05R\x06Counts\x12<\n" +
	"\vCreatedTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vCreatedTime\x12<\n" +
	"\vUpdatedTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vUpdatedTime\x12<\n" +
	"\vExpiredTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vExpiredTime\"X\n" +
	"\x14BargainInfoDeleteReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x05R\x06UserId\x12\x18\n" +
	"\aGoodsId\x18\x02 \x01(\x05R\aGoodsId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\x05R\x02Id\"\x92\x02\n" +
	"\x14BargainInfoDeleteRes\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x05R\x06UserId\x12\x18\n" +
	"\aGoodsId\x18\x03 \x01(\x05R\aGoodsId\x12<\n" +
	"\vCreatedTime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vCreatedTime\x12<\n" +
	"\vUpdatedTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vUpdatedTime\x12<\n" +
	"\vDeletedTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vDeletedTime2\x9f\x02\n" +
	"\fbargain_info\x12[\n" +
	"\aGetList\x12&.bargain_info.v1.BargainInfoGetListReq\x1a&.bargain_info.v1.BargainInfoGetListRes\"\x00\x12X\n" +
	"\x06Create\x12%.bargain_info.v1.BargainInfoCreateReq\x1a%.bargain_info.v1.BargainInfoCreateRes\"\x00\x12X\n" +
	"\x06Delete\x12%.bargain_info.v1.BargainInfoDeleteReq\x1a%.bargain_info.v1.BargainInfoDeleteRes\"\x00B\fZ\n" +
	"./templateb\x06proto3"

var (
	file_bargain_info_v1_bargain_info_proto_rawDescOnce sync.Once
	file_bargain_info_v1_bargain_info_proto_rawDescData []byte
)

func file_bargain_info_v1_bargain_info_proto_rawDescGZIP() []byte {
	file_bargain_info_v1_bargain_info_proto_rawDescOnce.Do(func() {
		file_bargain_info_v1_bargain_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bargain_info_v1_bargain_info_proto_rawDesc), len(file_bargain_info_v1_bargain_info_proto_rawDesc)))
	})
	return file_bargain_info_v1_bargain_info_proto_rawDescData
}

var file_bargain_info_v1_bargain_info_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bargain_info_v1_bargain_info_proto_goTypes = []any{
	(*BargainInfoCreateReq)(nil),  // 0: bargain_info.v1.BargainInfoCreateReq
	(*BargainInfoCreateRes)(nil),  // 1: bargain_info.v1.BargainInfoCreateRes
	(*BargainInfoGetListReq)(nil), // 2: bargain_info.v1.BargainInfoGetListReq
	(*BargainInfoGetListRes)(nil), // 3: bargain_info.v1.BargainInfoGetListRes
	(*BargainInfoDeleteReq)(nil),  // 4: bargain_info.v1.BargainInfoDeleteReq
	(*BargainInfoDeleteRes)(nil),  // 5: bargain_info.v1.BargainInfoDeleteRes
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_bargain_info_v1_bargain_info_proto_depIdxs = []int32{
	6,  // 0: bargain_info.v1.BargainInfoCreateRes.CreatedTime:type_name -> google.protobuf.Timestamp
	6,  // 1: bargain_info.v1.BargainInfoCreateRes.ExpiredTime:type_name -> google.protobuf.Timestamp
	6,  // 2: bargain_info.v1.BargainInfoGetListRes.CreatedTime:type_name -> google.protobuf.Timestamp
	6,  // 3: bargain_info.v1.BargainInfoGetListRes.UpdatedTime:type_name -> google.protobuf.Timestamp
	6,  // 4: bargain_info.v1.BargainInfoGetListRes.ExpiredTime:type_name -> google.protobuf.Timestamp
	6,  // 5: bargain_info.v1.BargainInfoDeleteRes.CreatedTime:type_name -> google.protobuf.Timestamp
	6,  // 6: bargain_info.v1.BargainInfoDeleteRes.UpdatedTime:type_name -> google.protobuf.Timestamp
	6,  // 7: bargain_info.v1.BargainInfoDeleteRes.DeletedTime:type_name -> google.protobuf.Timestamp
	2,  // 8: bargain_info.v1.bargain_info.GetList:input_type -> bargain_info.v1.BargainInfoGetListReq
	0,  // 9: bargain_info.v1.bargain_info.Create:input_type -> bargain_info.v1.BargainInfoCreateReq
	4,  // 10: bargain_info.v1.bargain_info.Delete:input_type -> bargain_info.v1.BargainInfoDeleteReq
	3,  // 11: bargain_info.v1.bargain_info.GetList:output_type -> bargain_info.v1.BargainInfoGetListRes
	1,  // 12: bargain_info.v1.bargain_info.Create:output_type -> bargain_info.v1.BargainInfoCreateRes
	5,  // 13: bargain_info.v1.bargain_info.Delete:output_type -> bargain_info.v1.BargainInfoDeleteRes
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_bargain_info_v1_bargain_info_proto_init() }
func file_bargain_info_v1_bargain_info_proto_init() {
	if File_bargain_info_v1_bargain_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bargain_info_v1_bargain_info_proto_rawDesc), len(file_bargain_info_v1_bargain_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bargain_info_v1_bargain_info_proto_goTypes,
		DependencyIndexes: file_bargain_info_v1_bargain_info_proto_depIdxs,
		MessageInfos:      file_bargain_info_v1_bargain_info_proto_msgTypes,
	}.Build()
	File_bargain_info_v1_bargain_info_proto = out.File
	file_bargain_info_v1_bargain_info_proto_goTypes = nil
	file_bargain_info_v1_bargain_info_proto_depIdxs = nil
}
