// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: bargain_history/v1/bargain_history.proto

package template

import (
	reflect "reflect"
	_ "shop-goframe-micro-service-refacotor/app/goods/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 砍价信息-创建-请求体
type BargainHistoryCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BargainId     int32                  `protobuf:"varint,1,opt,name=BargainId,proto3" json:"BargainId,omitempty" dc:"帮砍的砍价信息id"` //帮砍的砍价信息id
	UserId        int32                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"帮砍的用户id"`         //帮砍的用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainHistoryCreateReq) Reset() {
	*x = BargainHistoryCreateReq{}
	mi := &file_bargain_history_v1_bargain_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainHistoryCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainHistoryCreateReq) ProtoMessage() {}

func (x *BargainHistoryCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_bargain_history_v1_bargain_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainHistoryCreateReq.ProtoReflect.Descriptor instead.
func (*BargainHistoryCreateReq) Descriptor() ([]byte, []int) {
	return file_bargain_history_v1_bargain_history_proto_rawDescGZIP(), []int{0}
}

func (x *BargainHistoryCreateReq) GetBargainId() int32 {
	if x != nil {
		return x.BargainId
	}
	return 0
}

func (x *BargainHistoryCreateReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 砍价信息-创建-响应体
type BargainHistoryCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"砍价记录id"`                  // 砍价记录id
	BargainId     int32                  `protobuf:"varint,2,opt,name=BargainId,proto3" json:"BargainId,omitempty" dc:"帮砍价的信息id"`  // 帮砍价的信息id
	Amount        int32                  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty" dc:"本次砍价砍的金额数量"`      // 本次砍价砍的金额数量
	UserId        int32                  `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"帮砍的用户id"`         // 帮砍的用户id
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty" dc:"本次砍价时间"` // 本次砍价时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainHistoryCreateRes) Reset() {
	*x = BargainHistoryCreateRes{}
	mi := &file_bargain_history_v1_bargain_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainHistoryCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainHistoryCreateRes) ProtoMessage() {}

func (x *BargainHistoryCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_bargain_history_v1_bargain_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainHistoryCreateRes.ProtoReflect.Descriptor instead.
func (*BargainHistoryCreateRes) Descriptor() ([]byte, []int) {
	return file_bargain_history_v1_bargain_history_proto_rawDescGZIP(), []int{1}
}

func (x *BargainHistoryCreateRes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BargainHistoryCreateRes) GetBargainId() int32 {
	if x != nil {
		return x.BargainId
	}
	return 0
}

func (x *BargainHistoryCreateRes) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BargainHistoryCreateRes) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BargainHistoryCreateRes) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

// 砍价信息-查询-请求体
type BargainHistoryGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"砍价记录id"`          // 砍价记录id
	UserId        int32                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"帮砍的用户id"` // 帮砍的用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainHistoryGetListReq) Reset() {
	*x = BargainHistoryGetListReq{}
	mi := &file_bargain_history_v1_bargain_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainHistoryGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainHistoryGetListReq) ProtoMessage() {}

func (x *BargainHistoryGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_bargain_history_v1_bargain_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainHistoryGetListReq.ProtoReflect.Descriptor instead.
func (*BargainHistoryGetListReq) Descriptor() ([]byte, []int) {
	return file_bargain_history_v1_bargain_history_proto_rawDescGZIP(), []int{2}
}

func (x *BargainHistoryGetListReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BargainHistoryGetListReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 砍价信息-查询-响应体 待定
type BargainHistoryGetListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"砍价记录id"`                  // 砍价记录id
	BargainId     int32                  `protobuf:"varint,2,opt,name=BargainId,proto3" json:"BargainId,omitempty" dc:"帮砍的砍价信息id"` // 帮砍的砍价信息id
	Amount        int32                  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty" dc:"帮砍的金额"`           // 帮砍的金额
	UserId        int32                  `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"帮砍的用户id"`         // 帮砍的用户id
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty" dc:"创建时间"`   // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainHistoryGetListRes) Reset() {
	*x = BargainHistoryGetListRes{}
	mi := &file_bargain_history_v1_bargain_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainHistoryGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainHistoryGetListRes) ProtoMessage() {}

func (x *BargainHistoryGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_bargain_history_v1_bargain_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainHistoryGetListRes.ProtoReflect.Descriptor instead.
func (*BargainHistoryGetListRes) Descriptor() ([]byte, []int) {
	return file_bargain_history_v1_bargain_history_proto_rawDescGZIP(), []int{3}
}

func (x *BargainHistoryGetListRes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BargainHistoryGetListRes) GetBargainId() int32 {
	if x != nil {
		return x.BargainId
	}
	return 0
}

func (x *BargainHistoryGetListRes) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BargainHistoryGetListRes) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BargainHistoryGetListRes) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

// 砍价信息-删除-请求体
type BargainHistoryDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BargainId     int32                  `protobuf:"varint,1,opt,name=BargainId,proto3" json:"BargainId,omitempty" dc:"帮砍的砍价信息id"` //帮砍的砍价信息id
	UserId        int32                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"帮砍的用户id"`         //帮砍的用户id
	Id            int32                  `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty" dc:"实际的id"`                   //实际的id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainHistoryDeleteReq) Reset() {
	*x = BargainHistoryDeleteReq{}
	mi := &file_bargain_history_v1_bargain_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainHistoryDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainHistoryDeleteReq) ProtoMessage() {}

func (x *BargainHistoryDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_bargain_history_v1_bargain_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainHistoryDeleteReq.ProtoReflect.Descriptor instead.
func (*BargainHistoryDeleteReq) Descriptor() ([]byte, []int) {
	return file_bargain_history_v1_bargain_history_proto_rawDescGZIP(), []int{4}
}

func (x *BargainHistoryDeleteReq) GetBargainId() int32 {
	if x != nil {
		return x.BargainId
	}
	return 0
}

func (x *BargainHistoryDeleteReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BargainHistoryDeleteReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 砍价信息-删除-请求体
type BargainHistoryDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"砍价记录id"`                  // 砍价记录id
	BargainId     int32                  `protobuf:"varint,2,opt,name=BargainId,proto3" json:"BargainId,omitempty" dc:"帮砍的砍价信息id"` // 帮砍的砍价信息id
	UserId        int32                  `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"帮砍的用户id"`         // 帮砍的用户id
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty" dc:"创建时间"`   // 创建时间
	DeletedTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=DeletedTime,proto3" json:"DeletedTime,omitempty" dc:"删除时间"`   // 删除时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainHistoryDeleteRes) Reset() {
	*x = BargainHistoryDeleteRes{}
	mi := &file_bargain_history_v1_bargain_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainHistoryDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainHistoryDeleteRes) ProtoMessage() {}

func (x *BargainHistoryDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_bargain_history_v1_bargain_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainHistoryDeleteRes.ProtoReflect.Descriptor instead.
func (*BargainHistoryDeleteRes) Descriptor() ([]byte, []int) {
	return file_bargain_history_v1_bargain_history_proto_rawDescGZIP(), []int{5}
}

func (x *BargainHistoryDeleteRes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BargainHistoryDeleteRes) GetBargainId() int32 {
	if x != nil {
		return x.BargainId
	}
	return 0
}

func (x *BargainHistoryDeleteRes) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BargainHistoryDeleteRes) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *BargainHistoryDeleteRes) GetDeletedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedTime
	}
	return nil
}

var File_bargain_history_v1_bargain_history_proto protoreflect.FileDescriptor

const file_bargain_history_v1_bargain_history_proto_rawDesc = "" +
	"\n" +
	"(bargain_history/v1/bargain_history.proto\x12\x12bargain_history.v1\x1a\x1epbentity/bargain_history.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n" +
	"\x17BargainHistoryCreateReq\x12\x1c\n" +
	"\tBargainId\x18\x01 \x01(\x05R\tBargainId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x05R\x06UserId\"\xb5\x01\n" +
	"\x17BargainHistoryCreateRes\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x1c\n" +
	"\tBargainId\x18\x02 \x01(\x05R\tBargainId\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\x05R\x06Amount\x12\x16\n" +
	"\x06UserId\x18\x04 \x01(\x05R\x06UserId\x12<\n" +
	"\vCreatedTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vCreatedTime\"B\n" +
	"\x18BargainHistoryGetListReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x05R\x06UserId\"\xb6\x01\n" +
	"\x18BargainHistoryGetListRes\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x1c\n" +
	"\tBargainId\x18\x02 \x01(\x05R\tBargainId\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\x05R\x06Amount\x12\x16\n" +
	"\x06UserId\x18\x04 \x01(\x05R\x06UserId\x12<\n" +
	"\vCreatedTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vCreatedTime\"_\n" +
	"\x17BargainHistoryDeleteReq\x12\x1c\n" +
	"\tBargainId\x18\x01 \x01(\x05R\tBargainId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x05R\x06UserId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\x05R\x02Id\"\xdb\x01\n" +
	"\x17BargainHistoryDeleteRes\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x1c\n" +
	"\tBargainId\x18\x02 \x01(\x05R\tBargainId\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\x05R\x06UserId\x12<\n" +
	"\vCreatedTime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vCreatedTime\x12<\n" +
	"\vDeletedTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vDeletedTime2\xc6\x02\n" +
	"\x0fbargain_history\x12g\n" +
	"\aGetList\x12,.bargain_history.v1.BargainHistoryGetListReq\x1a,.bargain_history.v1.BargainHistoryGetListRes\"\x00\x12d\n" +
	"\x06Create\x12+.bargain_history.v1.BargainHistoryCreateReq\x1a+.bargain_history.v1.BargainHistoryCreateRes\"\x00\x12d\n" +
	"\x06Delete\x12+.bargain_history.v1.BargainHistoryDeleteReq\x1a+.bargain_history.v1.BargainHistoryDeleteRes\"\x00B\fZ\n" +
	"./templateb\x06proto3"

var (
	file_bargain_history_v1_bargain_history_proto_rawDescOnce sync.Once
	file_bargain_history_v1_bargain_history_proto_rawDescData []byte
)

func file_bargain_history_v1_bargain_history_proto_rawDescGZIP() []byte {
	file_bargain_history_v1_bargain_history_proto_rawDescOnce.Do(func() {
		file_bargain_history_v1_bargain_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bargain_history_v1_bargain_history_proto_rawDesc), len(file_bargain_history_v1_bargain_history_proto_rawDesc)))
	})
	return file_bargain_history_v1_bargain_history_proto_rawDescData
}

var file_bargain_history_v1_bargain_history_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bargain_history_v1_bargain_history_proto_goTypes = []any{
	(*BargainHistoryCreateReq)(nil),  // 0: bargain_history.v1.BargainHistoryCreateReq
	(*BargainHistoryCreateRes)(nil),  // 1: bargain_history.v1.BargainHistoryCreateRes
	(*BargainHistoryGetListReq)(nil), // 2: bargain_history.v1.BargainHistoryGetListReq
	(*BargainHistoryGetListRes)(nil), // 3: bargain_history.v1.BargainHistoryGetListRes
	(*BargainHistoryDeleteReq)(nil),  // 4: bargain_history.v1.BargainHistoryDeleteReq
	(*BargainHistoryDeleteRes)(nil),  // 5: bargain_history.v1.BargainHistoryDeleteRes
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_bargain_history_v1_bargain_history_proto_depIdxs = []int32{
	6, // 0: bargain_history.v1.BargainHistoryCreateRes.CreatedTime:type_name -> google.protobuf.Timestamp
	6, // 1: bargain_history.v1.BargainHistoryGetListRes.CreatedTime:type_name -> google.protobuf.Timestamp
	6, // 2: bargain_history.v1.BargainHistoryDeleteRes.CreatedTime:type_name -> google.protobuf.Timestamp
	6, // 3: bargain_history.v1.BargainHistoryDeleteRes.DeletedTime:type_name -> google.protobuf.Timestamp
	2, // 4: bargain_history.v1.bargain_history.GetList:input_type -> bargain_history.v1.BargainHistoryGetListReq
	0, // 5: bargain_history.v1.bargain_history.Create:input_type -> bargain_history.v1.BargainHistoryCreateReq
	4, // 6: bargain_history.v1.bargain_history.Delete:input_type -> bargain_history.v1.BargainHistoryDeleteReq
	3, // 7: bargain_history.v1.bargain_history.GetList:output_type -> bargain_history.v1.BargainHistoryGetListRes
	1, // 8: bargain_history.v1.bargain_history.Create:output_type -> bargain_history.v1.BargainHistoryCreateRes
	5, // 9: bargain_history.v1.bargain_history.Delete:output_type -> bargain_history.v1.BargainHistoryDeleteRes
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bargain_history_v1_bargain_history_proto_init() }
func file_bargain_history_v1_bargain_history_proto_init() {
	if File_bargain_history_v1_bargain_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bargain_history_v1_bargain_history_proto_rawDesc), len(file_bargain_history_v1_bargain_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bargain_history_v1_bargain_history_proto_goTypes,
		DependencyIndexes: file_bargain_history_v1_bargain_history_proto_depIdxs,
		MessageInfos:      file_bargain_history_v1_bargain_history_proto_msgTypes,
	}.Build()
	File_bargain_history_v1_bargain_history_proto = out.File
	file_bargain_history_v1_bargain_history_proto_goTypes = nil
	file_bargain_history_v1_bargain_history_proto_depIdxs = nil
}
