// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: bargain_history/v1/bargain_history.proto

package template

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BargainHistory_GetList_FullMethodName = "/bargain_history.v1.bargain_history/GetList"
	BargainHistory_Create_FullMethodName  = "/bargain_history.v1.bargain_history/Create"
	BargainHistory_Delete_FullMethodName  = "/bargain_history.v1.bargain_history/Delete"
)

// BargainHistoryClient is the client API for BargainHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BargainHistoryClient interface {
	GetList(ctx context.Context, in *BargainHistoryGetListReq, opts ...grpc.CallOption) (*BargainHistoryGetListRes, error)
	Create(ctx context.Context, in *BargainHistoryCreateReq, opts ...grpc.CallOption) (*BargainHistoryCreateRes, error)
	Delete(ctx context.Context, in *BargainHistoryDeleteReq, opts ...grpc.CallOption) (*BargainHistoryDeleteRes, error)
}

type bargainHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewBargainHistoryClient(cc grpc.ClientConnInterface) BargainHistoryClient {
	return &bargainHistoryClient{cc}
}

func (c *bargainHistoryClient) GetList(ctx context.Context, in *BargainHistoryGetListReq, opts ...grpc.CallOption) (*BargainHistoryGetListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BargainHistoryGetListRes)
	err := c.cc.Invoke(ctx, BargainHistory_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bargainHistoryClient) Create(ctx context.Context, in *BargainHistoryCreateReq, opts ...grpc.CallOption) (*BargainHistoryCreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BargainHistoryCreateRes)
	err := c.cc.Invoke(ctx, BargainHistory_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bargainHistoryClient) Delete(ctx context.Context, in *BargainHistoryDeleteReq, opts ...grpc.CallOption) (*BargainHistoryDeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BargainHistoryDeleteRes)
	err := c.cc.Invoke(ctx, BargainHistory_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BargainHistoryServer is the server API for BargainHistory service.
// All implementations must embed UnimplementedBargainHistoryServer
// for forward compatibility.
type BargainHistoryServer interface {
	GetList(context.Context, *BargainHistoryGetListReq) (*BargainHistoryGetListRes, error)
	Create(context.Context, *BargainHistoryCreateReq) (*BargainHistoryCreateRes, error)
	Delete(context.Context, *BargainHistoryDeleteReq) (*BargainHistoryDeleteRes, error)
	mustEmbedUnimplementedBargainHistoryServer()
}

// UnimplementedBargainHistoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBargainHistoryServer struct{}

func (UnimplementedBargainHistoryServer) GetList(context.Context, *BargainHistoryGetListReq) (*BargainHistoryGetListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedBargainHistoryServer) Create(context.Context, *BargainHistoryCreateReq) (*BargainHistoryCreateRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBargainHistoryServer) Delete(context.Context, *BargainHistoryDeleteReq) (*BargainHistoryDeleteRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBargainHistoryServer) mustEmbedUnimplementedBargainHistoryServer() {}
func (UnimplementedBargainHistoryServer) testEmbeddedByValue()                        {}

// UnsafeBargainHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BargainHistoryServer will
// result in compilation errors.
type UnsafeBargainHistoryServer interface {
	mustEmbedUnimplementedBargainHistoryServer()
}

func RegisterBargainHistoryServer(s grpc.ServiceRegistrar, srv BargainHistoryServer) {
	// If the following call panics, it indicates UnimplementedBargainHistoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BargainHistory_ServiceDesc, srv)
}

func _BargainHistory_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BargainHistoryGetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BargainHistoryServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BargainHistory_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BargainHistoryServer).GetList(ctx, req.(*BargainHistoryGetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BargainHistory_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BargainHistoryCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BargainHistoryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BargainHistory_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BargainHistoryServer).Create(ctx, req.(*BargainHistoryCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BargainHistory_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BargainHistoryDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BargainHistoryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BargainHistory_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BargainHistoryServer).Delete(ctx, req.(*BargainHistoryDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BargainHistory_ServiceDesc is the grpc.ServiceDesc for BargainHistory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BargainHistory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bargain_history.v1.bargain_history",
	HandlerType: (*BargainHistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _BargainHistory_GetList_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _BargainHistory_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BargainHistory_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bargain_history/v1/bargain_history.proto",
}
