// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: coupon/v1/coupon.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CouponCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CouponId      uint32                 `protobuf:"varint,2,opt,name=CouponId,proto3" json:"CouponId,omitempty"`
	Status        uint32                 `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Amount        uint64                 `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponCreateReq) Reset() {
	*x = CouponCreateReq{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponCreateReq) ProtoMessage() {}

func (x *CouponCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponCreateReq.ProtoReflect.Descriptor instead.
func (*CouponCreateReq) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *CouponCreateReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CouponCreateReq) GetCouponId() uint32 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *CouponCreateReq) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CouponCreateReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CouponCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponCreateRes) Reset() {
	*x = CouponCreateRes{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponCreateRes) ProtoMessage() {}

func (x *CouponCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponCreateRes.ProtoReflect.Descriptor instead.
func (*CouponCreateRes) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *CouponCreateRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CouponCreateRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_coupon_v1_coupon_proto protoreflect.FileDescriptor

const file_coupon_v1_coupon_proto_rawDesc = "" +
	"\n" +
	"\x16coupon/v1/coupon.proto\x12\tcoupon.v1\"u\n" +
	"\x0fCouponCreateReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\rR\x06UserId\x12\x1a\n" +
	"\bCouponId\x18\x02 \x01(\rR\bCouponId\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\rR\x06Status\x12\x16\n" +
	"\x06Amount\x18\x04 \x01(\x04R\x06Amount\"E\n" +
	"\x0fCouponCreateRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2[\n" +
	"\rCouponService\x12J\n" +
	"\x10CreateUserCoupon\x12\x1a.coupon.v1.CouponCreateReq\x1a\x1a.coupon.v1.CouponCreateResB=Z;shop-goframe-micro-service-refacotor/app/user/api/coupon/v1b\x06proto3"

var (
	file_coupon_v1_coupon_proto_rawDescOnce sync.Once
	file_coupon_v1_coupon_proto_rawDescData []byte
)

func file_coupon_v1_coupon_proto_rawDescGZIP() []byte {
	file_coupon_v1_coupon_proto_rawDescOnce.Do(func() {
		file_coupon_v1_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coupon_v1_coupon_proto_rawDesc), len(file_coupon_v1_coupon_proto_rawDesc)))
	})
	return file_coupon_v1_coupon_proto_rawDescData
}

var file_coupon_v1_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_coupon_v1_coupon_proto_goTypes = []any{
	(*CouponCreateReq)(nil), // 0: coupon.v1.CouponCreateReq
	(*CouponCreateRes)(nil), // 1: coupon.v1.CouponCreateRes
}
var file_coupon_v1_coupon_proto_depIdxs = []int32{
	0, // 0: coupon.v1.CouponService.CreateUserCoupon:input_type -> coupon.v1.CouponCreateReq
	1, // 1: coupon.v1.CouponService.CreateUserCoupon:output_type -> coupon.v1.CouponCreateRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_coupon_v1_coupon_proto_init() }
func file_coupon_v1_coupon_proto_init() {
	if File_coupon_v1_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coupon_v1_coupon_proto_rawDesc), len(file_coupon_v1_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coupon_v1_coupon_proto_goTypes,
		DependencyIndexes: file_coupon_v1_coupon_proto_depIdxs,
		MessageInfos:      file_coupon_v1_coupon_proto_msgTypes,
	}.Build()
	File_coupon_v1_coupon_proto = out.File
	file_coupon_v1_coupon_proto_goTypes = nil
	file_coupon_v1_coupon_proto_depIdxs = nil
}
