server:
  address:     ":8199"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  logger:
    path: "./log"
    file: "{Y-m-d}.log"
    level: "all"
    stdout: true

etcd:
  address: "127.0.0.1:2379"