server:
  address: ":8199"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  logger:
    path: "./log"
    file: "{Y-m-d}.log"
    prefix: "公众号：王中阳：gateway-h5" # 日志内容输出前缀。默认为空
    level: "all"
    stdout: false
    rotateSize: 104857600
    rotateBackupLimit: 7
    ctxKeys: ["traceId"]
    timeFormat: "2006-01-02 15:04:05.000"

etcd:
  address: "etcd:2379"
  dialTimeout: "5s"


