// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: add_goods_info/v1/add_goods_info.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AddGoodsInfo_GetList_FullMethodName = "/add_goods_info.v1.AddGoodsInfo/GetList"
)

// AddGoodsInfoClient is the client API for AddGoodsInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddGoodsInfoClient interface {
	GetList(ctx context.Context, in *AddGoodsInfoGetListReq, opts ...grpc.CallOption) (*AddGoodsInfoGetListRes, error)
}

type addGoodsInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewAddGoodsInfoClient(cc grpc.ClientConnInterface) AddGoodsInfoClient {
	return &addGoodsInfoClient{cc}
}

func (c *addGoodsInfoClient) GetList(ctx context.Context, in *AddGoodsInfoGetListReq, opts ...grpc.CallOption) (*AddGoodsInfoGetListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGoodsInfoGetListRes)
	err := c.cc.Invoke(ctx, AddGoodsInfo_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddGoodsInfoServer is the server API for AddGoodsInfo service.
// All implementations must embed UnimplementedAddGoodsInfoServer
// for forward compatibility.
type AddGoodsInfoServer interface {
	GetList(context.Context, *AddGoodsInfoGetListReq) (*AddGoodsInfoGetListRes, error)
	mustEmbedUnimplementedAddGoodsInfoServer()
}

// UnimplementedAddGoodsInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddGoodsInfoServer struct{}

func (UnimplementedAddGoodsInfoServer) GetList(context.Context, *AddGoodsInfoGetListReq) (*AddGoodsInfoGetListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedAddGoodsInfoServer) mustEmbedUnimplementedAddGoodsInfoServer() {}
func (UnimplementedAddGoodsInfoServer) testEmbeddedByValue()                      {}

// UnsafeAddGoodsInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddGoodsInfoServer will
// result in compilation errors.
type UnsafeAddGoodsInfoServer interface {
	mustEmbedUnimplementedAddGoodsInfoServer()
}

func RegisterAddGoodsInfoServer(s grpc.ServiceRegistrar, srv AddGoodsInfoServer) {
	// If the following call pancis, it indicates UnimplementedAddGoodsInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AddGoodsInfo_ServiceDesc, srv)
}

func _AddGoodsInfo_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGoodsInfoGetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddGoodsInfoServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddGoodsInfo_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddGoodsInfoServer).GetList(ctx, req.(*AddGoodsInfoGetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AddGoodsInfo_ServiceDesc is the grpc.ServiceDesc for AddGoodsInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddGoodsInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "add_goods_info.v1.AddGoodsInfo",
	HandlerType: (*AddGoodsInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _AddGoodsInfo_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "add_goods_info/v1/add_goods_info.proto",
}
