// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"shop-goframe-micro-service-refacotor/app/goods/internal/dao/internal"
)

// bargainHistoryDao is the data access object for the table bargain_history.
// You can define custom methods on it to extend its functionality as needed.
type bargainHistoryDao struct {
	*internal.BargainHistoryDao
}

var (
	// BargainHistory is a globally accessible object for table bargain_history operations.
	BargainHistory = bargainHistoryDao{internal.NewBargainHistoryDao()}
)

// Add your custom methods and functionality below.
