server:
  address: ":8199"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  logger:
    path: "./log"
    file: "{Y-m-d}.log"
    prefix: "公众号：王中阳：gateway-resource" # 日志内容输出前缀。默认为空
    level: "all"
    stdout: false
    rotateSize: 104857600
    rotateBackupLimit: 7
    ctxKeys: ["traceId"]
    timeFormat: "2006-01-02 15:04:05.000"

etcd:
  address: "etcd:2379"
  dialTimeout: "5s"


# 七牛云配置（使用环境变量）
qiniu:
  accessKey: "${QINIU_ACCESS_KEY}"
  secretKey: "${QINIU_SECRET_KEY}"
  bucket: "goframegoods"
  domain: "http://t15zl18vd.hn-bkt.clouddn.com"
  uploadTokenExpire: 3600

database:
  default:
    link: "mysql:root:root@tcp(mysql:3306)/resource"
    debug: false
    maxOpenConns: 50
    maxIdleConns: 10
    connMaxLifetime: "30m"