server:
  address: ":8299"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  logger:
    path: "./log"
    file: "{Y-m-d}.log"
    prefix: "gateway-admin"
    level: "all"
    stdout: true
    rotateSize: 104857600
    rotateBackupLimit: 7
    ctxKeys: [ "traceId" ]
    timeFormat: "2006-01-02 15:04:05.000"

etcd:
  address: "etcd:2379"
