// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pbentity/bargain_history.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BargainHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                  //
	BargainId     int32                  `protobuf:"varint,2,opt,name=BargainId,proto3" json:"BargainId,omitempty"`    //
	Amount        int32                  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`          //
	UserId        int32                  `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`          //
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty"` //
	DeletedTime   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=DeletedTime,proto3" json:"DeletedTime,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BargainHistory) Reset() {
	*x = BargainHistory{}
	mi := &file_pbentity_bargain_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BargainHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BargainHistory) ProtoMessage() {}

func (x *BargainHistory) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_bargain_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BargainHistory.ProtoReflect.Descriptor instead.
func (*BargainHistory) Descriptor() ([]byte, []int) {
	return file_pbentity_bargain_history_proto_rawDescGZIP(), []int{0}
}

func (x *BargainHistory) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BargainHistory) GetBargainId() int32 {
	if x != nil {
		return x.BargainId
	}
	return 0
}

func (x *BargainHistory) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BargainHistory) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BargainHistory) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *BargainHistory) GetDeletedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedTime
	}
	return nil
}

var File_pbentity_bargain_history_proto protoreflect.FileDescriptor

const file_pbentity_bargain_history_proto_rawDesc = "" +
	"\n" +
	"\x1epbentity/bargain_history.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x01\n" +
	"\x0eBargainHistory\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x1c\n" +
	"\tBargainId\x18\x02 \x01(\x05R\tBargainId\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\x05R\x06Amount\x12\x16\n" +
	"\x06UserId\x18\x04 \x01(\x05R\x06UserId\x12<\n" +
	"\vCreatedTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vCreatedTime\x12<\n" +
	"\vDeletedTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vDeletedTimeB=Z;shop-goframe-micro-service-refacotor/app/goods/api/pbentityb\x06proto3"

var (
	file_pbentity_bargain_history_proto_rawDescOnce sync.Once
	file_pbentity_bargain_history_proto_rawDescData []byte
)

func file_pbentity_bargain_history_proto_rawDescGZIP() []byte {
	file_pbentity_bargain_history_proto_rawDescOnce.Do(func() {
		file_pbentity_bargain_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_bargain_history_proto_rawDesc), len(file_pbentity_bargain_history_proto_rawDesc)))
	})
	return file_pbentity_bargain_history_proto_rawDescData
}

var file_pbentity_bargain_history_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_bargain_history_proto_goTypes = []any{
	(*BargainHistory)(nil),        // 0: pbentity.BargainHistory
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_bargain_history_proto_depIdxs = []int32{
	1, // 0: pbentity.BargainHistory.CreatedTime:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.BargainHistory.DeletedTime:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pbentity_bargain_history_proto_init() }
func file_pbentity_bargain_history_proto_init() {
	if File_pbentity_bargain_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_bargain_history_proto_rawDesc), len(file_pbentity_bargain_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_bargain_history_proto_goTypes,
		DependencyIndexes: file_pbentity_bargain_history_proto_depIdxs,
		MessageInfos:      file_pbentity_bargain_history_proto_msgTypes,
	}.Build()
	File_pbentity_bargain_history_proto = out.File
	file_pbentity_bargain_history_proto_goTypes = nil
	file_pbentity_bargain_history_proto_depIdxs = nil
}
