// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package flash_sale

import (
	"shop-goframe-micro-service-refacotor/app/gateway-h5/api/flash_sale"
)

type ControllerV1 struct{}

func NewV1() flash_sale.IFlashSaleV1 {
	return &ControllerV1{}
}
