// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
	"shop-goframe-micro-service-refacotor/app/gateway-h5/api/user"
	"shop-goframe-micro-service-refacotor/utility"

	consignee_info "shop-goframe-micro-service-refacotor/app/user/api/consignee_info/v1"
)

type ControllerV1 struct {
	ConsigneeInfoClient consignee_info.ConsigneeInfoClient
}

func NewV1() user.IUserV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("user", grpcx.Client.ChainUnary(
		utility.GrpcClientTimeout,
	))
	return &ControllerV1{
		ConsigneeInfoClient: consignee_info.NewConsigneeInfoClient(conn),
	}
}
