server:
  address: ":8399"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  logger:
    path: "./log"
    file: "{Y-m-d}.log"
    prefix: "gateway-resource"
    level: "all"
    stdout: true
    rotateSize: 104857600
    rotateBackupLimit: 7
    ctxKeys: [ "traceId" ]
    timeFormat: "2006-01-02 15:04:05.000"

database:
  default:
    link: "mysql:root:CHANGE_ME_MYSQL_PASSWORD@tcp(mysql:3306)/resource"
    debug: false

etcd:
  address: "etcd:2379"

qiniu:
  accessKey: "CHANGE_ME_SECRET"
  secretKey: "CHANGE_ME_SECRET"
  bucket: "shop-camp"  # 请替换为您的七牛云存储桶名称
  domain: "https://shop-camp.dayu.club" # 请替换为您的七牛云访问域名
  expireTime: 604800 # 过期时间,单位为秒,一周过期
