grpc:
  name: "user"
  address: ":31001"
  logger:
    path: "./log"
    file: "{Y-m-d}.log"
    prefix: "user-service"
    level: "all"
    stdout: true
    rotateSize: 104857600
    rotateBackupLimit: 7
    ctxKeys: [ "traceId" ]
    timeFormat: "2006-01-02 15:04:05.000"

database:
  default:
    link: "mysql:root:zK8!pW#s&t@5g$E7hN*d@tcp(mysql:3306)/user"
    debug: false

etcd:
  address: "etcd:2379"

rabbitmq:
  default:
    host: "rabbitmq"
    port: "5672"
    user: "root"
    password: "root"
    vhost: "/"
  exchange:
    user: "user_events"
  queue:
    user:
      registered: "user_registered_queue"
  routingKey:
    user:
      registered: "user.registered"

wxMiniConf:
  appId: CHANGE_ME_WECHAT_APP_ID
  secret: 1faee0008ac4456ba196289330c7b0f8
