grpc:
  name:             "user"
  address:          ":31001"
  logger:
    path: "./log" # 日志文件路径。默认为空，表示关闭，仅输出到终端
    file: "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"
    prefix: "公众号：王中阳：user-service" # 日志内容输出前缀。方便在所有日志行里一眼认出是我们这个服务产生的。
    level: "all" # 日志输出级别
    stdout: true  # 日志是否同时输出到终端。默认true
    rotateSize: 104857600   # 100MB切割日志文件
    rotateBackupLimit: 7    # 保留7天日志
    # ctxKeys 告诉日志组件从 context 中提取指定键的值
    ctxKeys: [ "traceId" ]    # 自动记录链路追踪ID 自定义Context上下文变量名称，自动打印Context的变量到日志中
    timeFormat: "2006-01-02 15:04:05.000" # 精确到毫秒

database:
  default:
    link:  "mysql:root:root@tcp(127.0.0.1:3306)/user"
    debug:


etcd:
  address: "127.0.0.1:2379"

rabbitmq:
  default:
    host: "127.0.0.1"
    port: "5672"
    user: "root"
    password: "root"
    vhost: "/"
  exchange:
    user: "user_events"
  queue:
    user:
      registered: "user_registered_queue"
  routingKey:
    user:
      registered: "user.registered"